= file
:xmpldir: ../../../test/clino/io/file

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that adds function that simplify the use of files.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************** os
=== os

==== open_file_c
[source,c]
----
FILE* open_file_c( cChars path, char const mode[static 1] );
----

Wraps fopen and allows the use of chars as path.
The size of path should not be creates as 4096.

==== remove_file_c
[source,c]
----
bool remove( cChars path );
----

Wraps remove and allows the use of chars as path.
The size of path should not be creates as 4096.

//*********************************************************************** state
=== state

==== file_size_c
[source,c]
----
int64_t file_size_c( FILE* file );
----

Returns the size of the current file.

//****************************************************************** get and put
=== get and put

==== get_file_bytes_c
[source,c]
----
bool get_file_bytes_c( FILE* file, cVarBytes bytes[static 1] );
----

Reads bytes from the file into bytes.
Returns true if at least one byte have been read and no error occurs.

==== get_file_chars_c
[source,c]
----
bool get_file_chars_c( FILE* file, cVarChars chars[static 1] );
----

Reads chars from the file into chars.
Returns true if at least one char have been read and no error occurs.

==== put_file_bytes_c
[source,c]
----
bool put_file_bytes_c( FILE* file, cBytes bytes[static 1] );
----

Writes bytes to a file.
Returns true if all bytes can be written to a file and no error occurs.

==== put_file_chars_c
[source,c]
----
bool put_file_chars_c( FILE* file, cChars chars[static 1] );
----

Writes chars to a file.
Returns true if all chars can be written to a file and no error occurs.

//************************************************************************ util
=== util

==== read_binary_file_c
[source,c]
----
cVarBytes read_binary_file_c( cChars path );
----

Reads a whole binary file into the heap memory.
Returns an invalid slice if an error occurs.

==== read_text_file_c
[source,c]
----
cVarChars read_text_file_c( cChars path );
----

Reads a whole text file into the heap memory as C string.
The end marker of the C string is not part of the slice.
Returns an invalid slice if an error occurs.

==== write_binary_file_c
[source,c]
----
bool write_binary_file_c( cChars path, cBytes bytes );
----

Creates a binary file that consist of the bytes.
Returns fals if an error occurs.

.Example
[source,c]
----
include::{xmpldir}/write_binary_file.c[]
----

==== write_text_file_c
[source,c]
----
bool write_text_file_c( cChars path, cChars chars );
----

Creates a binary file that consist of the bytes.
Returns fals if an error occurs.

.Example
[source,c]
----
include::{xmpldir}/write_text_file.c[]
----