= read
:xmpldir: {testroot}/clingo/io/read

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that allows to read text with additional arguments.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Type and Definitions

//***************************************************************** definitions
=== definitions

[id='cREAD_ERROR_']
==== cREAD_ERROR_
[source,c]
----
#define cREAD_ERROR_
----

Defines the c_ReadError values and the corresponding messages.

[id='c_ReadError']
==== c_ReadError
[source,c]
----
enum c_WriteError {
   c_NotAbleToReadValue = 1,
   c_ToLargeReadFormat = 2,
   c_InvalidReadFormat = 3,
};
type enum c_ReadError c_ReadError;
----

Enum type to represent errors that can happen in a read function.

==== c_read_va_arg
[source,c]
----
typedef int64_t ( *c_read_va_arg )( cScanner sca[static 1],
                                    void* val,
                                    cChars type,
                                    char const fmt[static 1] );
----

c_read_va_arg is the signature of a function to read a with type specified value
into val with the format fmt.
The default implementation of the function is read_format_arg_c.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== read_format_arg_c
[source,c]
----
int64_t read_format_arg_c( cScanner sca[static 1],
                           void* val,
                           cChars type,
                           char const fmt[static 1] );
----

Interprets val as pointer as type and reads the formated(fmt) text into it.

==== read_c
[source,c]
----
#define read_c_( Sca, ... )                                                    \
   read_c( (Sca), read_format_arg_c, nargs_c_( __VA_ARGS__ ), __VA_ARGS__ )
int64_t read_c( cScanner sca[static 1],
                c_read_va_arg read_arg,
                int n,
                ... );
----

Reads data from a scanner and can store them according to parameter specifier
into the variables given by the additional arguments.
A specifier has the following format:

----
{[!]type[:fmt]}
----

The optional "!"" at the beginning means that no variable is given by the
additional arguments for this value.
The optional "fmt" value can have a size of 32 chars.
The values `^` and `}` are special characters, use `^^` and `^}` to pass this
characters in the "fmt" value to the corresponding read function.

The requried type value shows witch sub read function will be used.
The default read_arg value read_format_arg_c uses the following mapping:

.type
[cols="1,3"]
|===
|bool |read_bool_c
|b    |read_byte_c
|c    |read_char_c
|i8   |read_int8_c
|i16  |read_int16_c
|i32  |read_int32_c
|i64  |read_int64_c
|r    |read_rune_c
|rng  |read_range_c
|u8   |read_uint8_c
|u16  |read_uint16_c
|u32  |read_uint32_c
|u64  |read_uint64_c
|===

Additional to the the specifiers can a format string also contain commands.
A command has the following format:

----
{[type]op(func/range/set)}
----

The values `^` and `}` are special characters, use `^^` and `^}` to pass this
characters to the set or range value.

If no "type" value is set expects the function a set of runes.
The command will use, dependent on "op", the following functions with the set:

.set operations
[cols="1,3,3"]
|===
|> |move_to_any_rune_c |
|= |move_if_any_rune_c | 1 occurrence
|? |move_if_any_rune_c | optional (0 or 1 occurrence)
|+ |move_while_any_rune_c | 1 or more repetitions
|* |move_while_any_rune_c | 0 or more repetitions
|===

If "type" is `/` expects the function one of the following letters: 

.func values
[cols="1,3"]
|===
|a |isalpha
|c |iscntrl
|d |isdigit
|g |isgraph
|l |islower
|o |isprint
|p |ispunct
|s |isspace
|u |isupper
|w |isalnum
|x |isxdigit
|===

The command will use, dependent on "op", the following functions with the func:

.func operations
[cols="1,3,3"]
|===
|> |move_to_char_match_c |
|= |move_if_char_match_c | 1 occurrence
|? |move_if_char_match_c | optional (0 or 1 occurrence)
|+ |move_while_char_match_c | 1 or more repetitions
|* |move_while_char_match_c | 0 or more repetitions
|===

If "type" is `[` expects the function a rune range value.
A rune range value can have two representations:

----
unicode number range:
"0020-007e"
"20-7E"
just min and max rune:
" ~"
"az"
----

The command will use, dependent on "op", the following functions with the range:

.range operations
[cols="1,3,3"]
|===
|> |move_to_in_range_c |
|= |move_if_in_range_c | 1 occurrence
|? |move_if_in_range_c | optional (0 or 1 occurrence)
|+ |move_while_in_range_c | 1 or more repetitions
|* |move_while_in_range_c | 0 or more repetitions
|===

.Example
[source,c]
----
include::{xmpldir}/read.c[]
----

//*********************************************************************** error
=== error

==== read_error_msg_c
[source,c]
----
char const* read_error_msg_c( cScanner sca[static 1] );
----

Returns the corresponding message for a C_ReadError.
