= chunk
:xmpldir: ../../../test/clingo/lang/chunk

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

A chunk is a abstract struct that allows to iterate over multiple values of a
slice.
The subslices(chunks) are not overlapping.

A chunk struct can also be viewed as slice because it has the attributes s
(sequence length) and v (points to the first value).

image:chunk.svg[]

In addition has a chunk the attributes fav (favored size) and slice (the
actual slice).

This module defines code generation macros to generate typed chunk structs.
Also has this module macro functions to init and use a chunk struct to move
along the slice sequence.

//******************************************************************************
//****************************************************** Code Generation Macros
//******************************************************************************
== Code Generation Macros

//************************************************************************ type
=== type

[id='CHUNK_C_']
==== CHUNK_C_
[source,c]
----
#define CHUNK_C_( Type, SliceType, ChunkType )
----

Generates a chunk struct for a slice with _Type_ values.
The overview shows the generated structs and functions for the call.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ init
=== init

[id='back_chunk_c_']
==== back_chunk_c_
[source,c]
----
#define back_chunk_c_( Size, Slice )
----

Initializes a chunk on the back of the Slice.
The Size parameter defines the size of the chunk subslices.

[id='front_chunk_c_']
==== front_chunk_c_
[source,c]
----
#define front_chunk_c_( Size, Slice )
----

Initializes a chunk on the front of the Slice.
The Size paramter defines the size of the chunk subslices.

//************************************************************************* use
=== use

[id='exact_chunk_c_']
==== exact_chunk_c_
[source,c]
----
#define exact_chunk_c_( Chunk )
----

Returns true if the chunk is valid and s equates to fav.

.Example
[source,c]
----
include::{xmpldir}/exact_chunk.c[]
----

[id='next_chunk_c_']
==== next_chunk_c_
[source,c]
----
#define next_chunk_c_( Chunk )
----

Moves the chunk forward.

.Example
[source,c]
----
include::{xmpldir}/next_chunk.c[]
----

[id='prev_chunk_c_']
==== prev_chunk_c_
[source,c]
-----
#define prev_chunk_c_( Chunk )
-----

Moves the chunk backward.

.Example
[source,c]
----
include::{xmpldir}/prev_chunk.c[]
----

[id='valid_chunk_c_']
==== valid_chunk_c_
[source,c]
----
#define valid_chunk_c_( Chunk )
----

Returns true if the chunk is a valid subslice of the slice, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/valid_chunk.c[]
----
