= chunk
:xmpldir: ../../../test/clingo/lang/chunk

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

A chunk is a abstract struct that allows to iterate over multiple values of a
slice.
The subslices(chunks) are not overlapping.

A chunk struct can also be viewed as slice because it has the attributes s
(sequence length) and v (points to the first value).

image:chunk.svg[]

In addition has a chunk the attributes favSize (favored size) and slice (the
actual slice).

This module defines code generation macros to generate typed chunk structs.
Also has this module macro functions to init and use a chunk struct to move
along the slice sequence.

//******************************************************************************
//****************************************************** Code Generation Macros
//******************************************************************************
== Code Generation Macros

//************************************************************************ init
=== init

[id='INIT_FRONT_CHUNK_C_']
==== INIT_FRONT_CHUNK_C_
[source,c]
----
#define INIT_FRONT_CHUNK_C_( FuncName, ChunkType, SliceType )
----

Generates a initialization function that sets the chunk on the front of a
slice.
The parameter s defines the size of the chunk subslices.
The generated function has the following common signature:
[source,c]
----
void FuncName( ChunkType chunk[static 1], int64_t s, SliceType slice );
----

[id='INIT_BACK_CHUNK_C_']
==== INIT_BACK_CHUNK_C_
[source,c]
----
#define INIT_FRONT_CHUNK_C_( FuncName, ChunkType, SliceType )
----

Generates a initialization function that sets the chunk on the back of a
slice.
The parameter s defines the size of the chunk subslices.
The generated function has the following common signature.
[source,c]
----
void FuncName( ChunkType chunk[static 1], int64_t s, SliceType slice );
----

//************************************************************************ type
=== type

[id='CHUNK_DEF_C_']
==== CHUNK_DEF_C_
[source,c]
----
#define CHUNK_DEF_C_( Type,
                      ChunkType, SliceType, FuncSuffix,
                      VarChunkType, VarSliceType, VarFuncSuffix )
----

Generates two chunk structs for slices with Type values.
The struct ChunkType for the const sequence of SliceType and
VarChunkType for the variable sequence of VarSliceType.
The values FuncSuffix and VarFuncSuffix are used as postfix for the generated
inline functions.

The following call can be used in a .h or .c file.
[source,c]
----
CHUNK_DEF_C_(
   char,             // Type
   cCharChunk,       // ChunkType
   cChars,           // SliceType
   char_chunk_c,     // FuncSuffix
   cVarCharChunk,    // VarChunkType
   cVarChars,        // VarSliceType
   var_char_chunk_c  // VarFuncSuffix
)
----
The overview shows the generated structs and functions for the call.

[options="header"]
|====
| | Const Data Chunk | Variable Data Chunk

| struct
| cCharChunk
| cVarCharChunk

| INIT_FRONT_CHUNK_C_
| init_front_char_chunk_c
| init_front_var_char_chunk_c

| INIT_BACK_CHUNK_C_
| init_back_char_chunk_c
| init_back_var_char_chunk_c
|====

[id='CHUNK_IMPL_C_']
==== CHUNK_IMPL_C_
[source,c]
----
#define CHUNK_IMPL_C_( ChunkType, SliceType, FuncSuffix,
                       VarChunkType, VarSliceType, VarFuncSuffix )
----

Generates the correspondent extern inline functions for the WINDOW_DEF_C_ macro.

[id='STATIC_FRONT_CHUNK_C_']
==== STATIC_FRONT_CHUNK_C_
[source,c]
----
#define STATIC_FRONT_CHUNK_C_( Type, ChunkType, SliceType, FuncSuffix )
----

Generates a chunk struct and the corresponding static INIT_FRONT_CHUNK_C_
function.

.Example
[source,c]
----
include::{xmpldir}/STATIC_FRONT_CHUNK.c[]
----

[id='STATIC_BACK_CHUNK_C_']
==== STATIC_BACK_CHUNK_C_
[source,c]
----
#define STATIC_BACK_CHUNK_C_( Type, ChunkType, SliceType, FuncSuffix )
----

Generates a chunk struct and the corresponding static INIT_BACK_CHUNK_C_
function.

.Example
[source,c]
----
include::{xmpldir}/STATIC_BACK_CHUNK.c[]
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

[id='exact_chunk_c_']
==== exact_chunk_c_
[source,c]
----
#define exact_chunk_c_( Chunk )
----

Returns true if the chunk is valid and s equates to favSize.

.Example
[source,c]
----
include::{xmpldir}/exact_chunk.c[]
----

[id='next_chunk_c_']
==== next_chunk_c_
[source,c]
----
#define next_chunk_c_( Chunk )
----

Moves the chunk forward.

.Example
[source,c]
----
include::{xmpldir}/next_chunk.c[]
----

[id='prev_chunk_c_']
==== prev_chunk_c_
[source,c]
-----
#define prev_chunk_c_( Chunk )
-----

Moves the chunk backward.

.Example
[source,c]
----
include::{xmpldir}/prev_chunk.c[]
----

[id='valid_chunk_c_']
==== valid_chunk_c_
[source,c]
----
#define valid_chunk_c_( Chunk )
----

Returns true if the chunk is a valid subslice of the slice, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/valid_chunk.c[]
----
