= error

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Instances of cError should allways be stored on an cErrorStack instance.
Each error can have custom information that can be stored after the cError
instance on a stack.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//*********************************************************************** error
=== error

[id='cNoError_']
==== cNoError_
[source,c]
----
#define cNoError_ 0
----

Macro that defines the error code value that represents no error.

[id='c_note_error']
==== c_note_error
[source,c]
----
typedef bool ( *c_note_error )( cRecorder rec[static 1], cError const* err );
----

Type definition of a note function for an cErrorType.

[id='cErrorType']
==== cErrorType
[source,c]
----
struct cErrorType
{
   char const* desc;
   c_note_error note;
};
typedef struct cErrorType cErrorType;
----

Stores information of that all error types share.
The attribute desc is a string that represents the content type, like C_ErrnoErrro for example.
The note function should also be the same for all instances of a cErrorType.

[id='cError']
==== cError
[source,c]
----
struct cError
{
   cErrorType const* type;
   cError const* sub;
};
typedef struct cError cError;
----

Struct to store error information.
A cError instance should allways exist on an cErrorStack and should have stored
the custom cErrorData directly after the cError.
The type value stores a s

The code allows to check and handle an error in the code.
The msg attribute allows to print or log the error.
The type value is a pointer to the shared cErrorType instance.
The sub value can point to an sub error that triggered the error.

==== cErrorStack
[source,c]
----
struct cErrorStack
{
   int64_t space;
   void* mem;
   cError const* err;
};
typedef struct cErrorStack cErrorStack;
----

A stack that should be used to store the cError instances with the corresponding
cErrorData. The err value points to the last error that was pushed on the stack.

//*********************************************************************** errno
=== errno

[id='C_ErrnoError']
==== C_ErrnoError
[source,c]
----
cErrorType const C_ErrnoError;
----

Stores the cErrorType instance that all errors that represent an errno error
reference.

[id='cErrnoErro']
==== cErrnoError
[source,c]
----
struct cErrnoError
{
   int number;
};
typedef struct cErrnoError cErrnoError;
----

Stores the errno number that the error represents.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ error
=== error

[id='error_depth_c']
==== error_depth_c
[source,c]
----
int64_t error_depth_c( cError const err* );
----

Counts how much cError variables are chained together..

//************************************************************************ stack
=== stack

[id='error_stack_c_']
==== error_stack_c_
[source,c]
----
#define error_stack_c_( Size )
----

Allocates a byte array at the stack and assigns the memory to the error stack.

[id='heap_error_stack_c_']
==== heap_error_stack_c_
[source,c]
----
#define heap_error_stack_c_( Size )
----

Allocates a byte array at the heap and assigns the memory to a new created
error stack.

[id='make_error_stack_c_']
==== make_error_stack_c_
[source,c]
----
#define make_error_stack_c_( Size, Memory )
----

Creates a error stack with the allready allocated memory.

[id='count_errors_c']
==== count_errors_c
[source,c]
----
int64_t count_errors_c( cErrorStack es[static 1] );
----

Counts how much cError variables are chained together on the stack.

[id='drop_error_c']
==== drop_error_c
[source,c]
----
void drop_error_c( cErrorStack es[static 1] );
----

Drops the last pushed error from the stack.

[id='push_error_c']
==== push_error_c
[source,c]
----
bool push_error_c( cErrorStack es[static 1],
                   cErrorType const type[static 1],
                   cErrorData const* data,
                   int64_t dataSize );
----

Pushes a error on the stack with the corresponding cErrorData.

[id='reset_error_stack_c']
==== reset_error_stack_c
[source,c]
----
void reset_error_stack_c( cErrorStack es[static 1] );
----

Removes all chained errors from the stack.

//************************************************************************ errno
=== push error

[id='push_errno_error_c']
==== push_errno_error_c
[source,c]
----
bool push_errno_error_c( cErrorStack es[static 1], int number );
----

Function to push a errno error with the corresponding cErrorData on the stack.
