= slice
:xmpldir: {testroot}/clingo/lang/slice

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
[id='Overview']
== Overview

A slice is a abstract struct that refers to a segment of an array.
Each struct that has an attribute s (defines the sequence length) and v
(points to the first value of the sequence) can be viewed as a slice.

A slice does not own the referenced sequence, this allows to point with
different slices at the same array.

image:slice-pineapple.svg[]

It is best practice to define slice structs that just have the s and the v
attribute.
It is also recommended to use two kind of slices for a type or struct.
A slice type where v is a pointer to _const_ data and a slice that points
to variable data.

[options="header"]
|====
| Data Type | Const Data Slice | Variable Data Slice

| char
| cChars
| cVarChars

| int8_t
| cInt8s
| cVarInt8s
|====

This module defines code generation macros to generate typed slice structs.
Also has this module macro functions that work with all structs that can be
viewed as a slice.

//******************************************************************************
//****************************************************** Code Generation Macros
//******************************************************************************
[id='Code-Generation-Macros']
== Code Generation Macros

//************************************************************************ type
=== type

[id='SLICES_C_']
==== SLICES_C_
[source,c]
----
#define SLICES_C_( Type, SliceType, VarSliceType )
----

Generates two slices for sequences with Type values.
The struct SliceType for const sequences and VarSliceType for variable
sequences.

The following call can be used in a .h or .c file.
[source,c]
----
SLICES_C_(
   int8_t,        // Type
   cInt8s,    // SliceType
   cVarInt8s  // VarSliceType
)
----

//************************************************************************ type
=== type

[id='TEMP_SLICE_C_']
==== TEMP_SLICE_C_
[source,c]
----
#define TEMP_SLICE_C_( Entry, EntryStruct )
----

Generates a struct with the name Entry and a slice with the composed name
EntrySlice.
The Entry struct will have the in EntryStruct defined structure.

.Example
[source,c]
----
include::{xmpldir}/TEMP_SLICE_DEF.c[]
----

[id='TEMP_VAR_SLICE_C_
==== TEMP_VAR_SLICE_C_
[source,c]
----
#define TEMP_VAR_SLICE_C_( Entry, EntryStruct )
----

Generates a struct with the name Entry and a var slice with the composed name
EntrySlice.
The Entry struct will have the in EntryStruct defined structure.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ init
=== init

[id='as_c_']
==== as_c_
[source,c]
----
#define as_c_( SliceType, Slice )
----

A macro function that converts a abstract slice to a slice with the SliceType.

[id='atween_c_']
==== atween_c_
[source,c]
----
#define atween_c_( Beg, End )
----

A macro function that returns a slice that is defined with a
pointer at the first element and a pointer after the last element.

.Example
[source,c]
----
include::{xmpldir}/atween.c[]
----

[id='empty_c_']
==== empty_c_
[source,c]
----
#define empty_c_() 
----

A macro function to initialse an empty slice where s is 0 and v is NULL.

[id='heap_slice_c_']
==== heap_slice_c_
[source,c]
----
#define heap_slice_c_( Size, Type )
----

A macro function for the initialization of a slice with a sequence that will be
allocated on the heap.
Size defines the length of the sequence.
Type defines the data type of the values in the sequence.

[id='invalid_c_']
==== invalid_c_
[source,c]
----
#define invalid_c_()
----

A macro function to initialse an invalid slice.

[id='scalars_c_']
==== scalars_c_
[source,c]
----
#define scalars_c_( Size, Type )
----

A macro function for the initializaiton of a slice with a sequence of scalar
values.
Size defines the length of the sequence.
Type defines the data type of the values in the sequence.

.Example
[source,c]
----
include::{xmpldir}/scalars.c[]
----

[id='slice_c_']
==== slice_c_
[source,c]
----
#define slice_c_( Type, ... )
----

A macro function for the initialization of a slice with a sequence.
Type defines the data type of the values in the sequence.
The additional arguments(...) represent the values that the sequence should
have.

.Example
[source,c]
----
include::{xmpldir}/slice.c[]
----

[id='structs_c_']
==== structs_c_
[source,c]
----
#define structs_c_( Size, Type )
----

A macro function for the initializaiton of a slice with a sequence of structs.
Size defines the length of the sequence.
Type defines the data type of the values in the sequence.

.Example
[source,c]
----
include::{xmpldir}/structs.c[]
----

//************************************************************************* sub
=== sub

[id='left_c_']
==== left_c_
[source,c]
----
#define left_c_( SliceType, Slice, MaxLen )
----

A macro function that returns a sub-slice that contains the leftmost values
of a slice.
If maxLen is greater or equal the s value of slice, contains the sub-slice
all values from the slice.

.Example
[source,c]
----
include::{xmpldir}/left.c
----

[id='mid_c_']
==== mid_c_
[source,c]
----
#define mid_c_( SliceType, Slice, Idx )
----

A macro function that returns a sub-slice starting(including) at a given
index.
If index does not point into the slice returns the function an empty slice.

.Example
[source,c]
----
include::{xmpldir}/mid.c
----

[id='right_c_']
==== right_c_
[source,c]
----
#define right_c_( SliceType, Slice, MaxLen )
----

A macro function that return a sub-slice that contains the rightmost values
of a slice.
If maxLen is greater or equal as the s value of slice, contains the
sub-slice all values from the slice.

.Example
[source,c]
----
include::{xmpldir}/right.c
----

[id='sub_c_']
==== sub_c_
[source,c]
----
#define sub_c_( SliceType, Slice, BegIdx, EndIdx )
----

A macro function that returns a sub-slice of a given slice.
The returned sub-slice includes the value at begIdx(begin index) as first
value and the value at endIdx-1 as last value.
If begIdx or endIdx are not valid indices returns the function a empty
slice.

.Example
[source,c]
----
include::{xmpldir}/sub.c
----

//*********************************************************************** check
=== check

[id='is_empty_c_']
==== is_empty_c_
[source,c]
----
#define is_empty_c_( Slice )
----

Returns true if the Slice is empty, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/is_empty.c[]
----

[id='is_invalid_c_']
==== is_empty_c_
[source,c]
----
#define is_invalid_c_( Slice )
----

Returns true if the Slice is invalid, otherwise false.
A slice wiht a negative s value is invalid.

[id='is_sub_c_']
==== is_sub_c_
[source,c]
----
#define is_sub_c_( Main, Sub )
----

Returns true if Sub is a sub-slice from Main, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/is_sub.c[]
----

[id='valid_index_c_']
==== valid_index_c_
[source,c]
----
#define valid_index_c_( Slice, Index )
----

Checks if a Index is inside the size boundaries of the Slice.

.Example
[source,c]
----
include::{xmpldir}/valid_index.c[]
----

//********************************************************************** access
=== access

[id='first_c_']
==== first_c_
[source,c]
----
#define first_c_( Slice )
----

Returns the first value in the Slice.

.Example
[source,c]
----
include::{xmpldir}/first.c[]
----

[id='get_if_c_']
==== get_if_c_
[source,c]
----
#define get_if_c_( Slice, Index, Def )
----

Returns the value at the Index position in the Slice.
If the Index is invalid will the Def value returned.

.Example
[source,c]
----
include::{xmpldir}/get_if.c[]
----

[id='last_c_']
==== last_c_
[source,c]
----
#define last_c_( Slice )
----

Returns the last value in the Slice.

.Example
[source,c]
----
include::{xmpldir}/last.c[]
----

[id='set_if_c_']
==== set_if_c_
[source,c]
----
#define set_if_c_( Slice, Index, Value )
----

Updates the Value at the Index position in the Slice.
If the Index is invalid will no value be replaced.

.Example
[source,c]
----
include::{xmpldir}/set_if.c[]
----

//************************************************************** pointer access
=== pointer access

[id='begin_c_']
==== begin_c_
[source,c]
----
#define begin_c_( Slice )
----

Returns a pointer to the firts element of the sequence.

.Example
[source,c]
----
include::{xmpldir}/begin.c[]
----

[id='end_c_']
==== end_c_
[source,c]
----
#define end_c_( Slice )
----

Returns a pointer to the element past the last element of the sequence.

.Example
[source,c]
----
include::{xmpldir}/end.c[]
----

[id='each_c_']
==== each_c_
[source,c]
----
#define each_c_( Type, Itr, Slice )
----

Macro function to define a for statement to iterate over all elements in Slice.

.Example
[source,c]
----
include::{xmpldir}/each.c[]
----

[id='for_each_c_']
==== for_each_c_
[source,c]
----
#define for_each_c_( N, Type, Itr, Slice )
----

Macro function to define a for statement to iterate over all elements in Slice and gives also the index.

.Example
[source,c]
----
include::{xmpldir}/for_each.c[]
----

[id='nth_c_']
==== nth_c_
[source,c]
----
#define nth_c_( Slice, N )
----

Returns a pointer to value at the position N in the Slice.
Th N value can be negative to access the Slice backwards.
If the N value is out of range will NULL be returned.

.Example
[source,c]
----
include::{xmpldir}/nth.c[]
----

[id='index_of_c_']
==== index_of_c_
[source,c]
----
#define index_of_c_( Slice, Ptr )
----

Returns the index of the pointer Ptr.
If the pointer does not point to a value of the sequence returns the macro
function -1.

.Example
[source,c]
----
include::{xmpldir}/index_of.c[]
----

[id='points_into_c_']
==== points_into_c_
[source,c]
----
#define points_into_c_( Slice, Ptr )
----

Checks if the pointer Ptr points to a value in the sequence of the Slice.

.Example
[source,c]
----
include::{xmpldir}/points_into.c[]
----

[id='ptr_for_c_']
==== ptr_for_c_
[source,c]
----
#define ptr_for_c_( Slice, Index )
----

Returns a pointer to value at the Index position in the Slice.
If the Index is invalid will a null pointer returned.

.Example
[source,c]
----
include::{xmpldir}/ptr_for.c[]
----

[id='rbegin_c_']
==== rbegin_c_
[source,c]
----
#define rbegin_c_( Slice )
----

Returns a pointer to the last element of the sequence.

.Example
[source,c]
----
include::{xmpldir}/rbegin.c[]
----

[id='rend_c_']
==== rend_c_
[source,c]
----
#define rend_c_( Slice )
----

Returns a pointer to the element before the first element of the sequence.

.Example
[source,c]
----
include::{xmpldir}/rend.c[]
----

