= window
:xmpldir: {testroot}/clingo/lang/window

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

A window is a abstract struct that allows to itarate over multiple values of a
slice.
The subslices(windows) are overlapping.

A window struct can also be viewed as slice because it has the attributes *s*
(sequence length) and *v* (points to the first value).

image:window.svg[]

In addition has a window an attribute *slice* for the actual slice.

This module defines code generation macros to generate typed window structs.
Also has this module macro functions to init and use a window struct to move
along the slice sequence.

//******************************************************************************
//****************************************************** Code Generation Macros
//******************************************************************************
== Code Generation Macros

//************************************************************************ type
=== type

[id='WINDOW_C_']
==== WINDOW_C_
[source,c]
----
#define WINDOW_C_( Type, SliceType, WindowType )
----

Generates a window struct for a slice with _Type_ values.
The overview shows the generated structs and functions for the call.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ init
=== init

[id='back_window_c_']
==== back_window_c_
[source,c]
----
#define back_window_c_( Size, Slice )
----

Initializes a window on the back of the Slice.
The Size parameter defines the size of the window subslices.

[id='front_window_c_']
==== front_window_c_
[source,c]
----
#define front_window_c_( Size, Slice )
----

Initializes a window on the front of the Slice.
The Size parameter defines the size of the window subslices.

//************************************************************************* use
=== use

[id='next_window_c_']
==== next_window_c_
[source,c]
----
#define next_window_c_( Window )
----

Moves the window forward.

.Example
[source,c]
----
include::{xmpldir}/next_window.c[]
----

[id='prev_window_c_']
==== prev_window_c_
[source,c]
----
#define prev_window_c_( Window )
----

Moves the window backward.

.Example
[source,c]
----
include::{xmpldir}/prev_window.c[]
----

[id='valid_window_c_']
==== valid_window_c_
[source,c]
----
#define valid_window_c_( Window )
----

Returns true if the window is a valid subslice of the slice, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/valid_window.c[]
----
