= cMonthDay
:xmpldir: ../../../test/clingo/time/cMonthDay

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cMonthDay']
==== cMonthDay
[source,c]
----
struct cMonthDay
{
   c_Month month;
   int8_t day;
};
typedef struct cMonthDay cMonthDay;
----

The cMonthDay struct represents a day in a specific year that is not part of the
struct.

//******************************************************************* Generated
=== Generated

[id='cMonthDaySlice']
==== cMonthDaySlice
:Slice-Type: cMonthDay const
:Slice-Slice: cMonthDaySlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarMonthDaySlice']
==== cVarMonthDaySlice
:Slice-Type: cMonthDay
:Slice-Slice: cVarMonthDaySlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_month_day_c
[source,c]
----
int cmp_month_day_c( cMonthDay a, cMonthDay b );
----

Compares two cMonthDay values and returns the three possible results:

<0:: if a is earlier as b
0:: if both dates are equal
>0:: if a is later as b

.Example
[source,c]
----
include::{xmpldir}/cmp_month_day.c[]
----

==== month_day_c
[source,c]
----
cMonthDay month_day_c( int64_t month, int64_t day );
----

Initialise a cMonthDay value with a month and day value.

//************************************************************************** io
=== io

The functions read_month_day_c and write_month_day_c are using the following
format:

.format
[cols="1,2,1"]
|===
|D |The day as a number without a leading character |1 to 31
|_D |The day as a number with a leading space |1 to 31
|DD |The day as a number with a leading zero |01 to 31
|M |The month as a number without a leading character |1 to 12
|_M |The month as a number with a leading space |1 to 12
|MM |The month as a number with a leading zero |01 to 12
|MMM |The abbreviated localized month name |Jan' to Dec
|===

==== read_month_day_c
[source,c]
----
#define read_month_day_c_( Sca, MonthDay )                                     \
   read_month_day_c( (Sca), (MonthDay), "" )
bool read_month_day_c( cScanner sca[static 1],
                       cMonthDay md[static 1],
                       char const fmt[static 1] );
----

Reads a cMonthDay value from a text with a scanner.
The function will use "MMM._D" as default format.

.Example
[source,c]
----
include::{xmpldir}/read_month_day.c[]
----

==== write_month_day_c
[source,c]
----
#define write_month_day_c_( Rec, MonthDay )                                    \
   write_month_day_c( (Rec), (MonthDay), "" )
bool write_month_day_c( cRecorder rec[static 1],
                        cMonthDay md,
                        char const fmt[static 1] );
----

Writes a cMonthDay value into the recorder.
The function will use "MMM._D" as default format.

.Example
[source,c]
----
include::{xmpldir}/write_month_day.c[]
----
