= cTimestamp
:xmpldir: ../../../test/clingo/time/cTimestamp

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Provides a struct and a set of function to work with a moment in time.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cTimestamp']
==== cTimestamp
[source,c]
----
struct cTimestamp
{
   int64_t _v;
};
typedef struct cTimestamp cTimestamp;
----

A cTimestamp value represents a moment in time.

//******************************************************************* Generated
=== Generated

[id='cTimestampSlice']
==== cTimestampSlice
[source,c]
----
struct cTimestampSlice
{
int64_t s;
cTimestamp const* v;
};
typedef struct cTimestampSlice cTimestampSlice;
----

{Slice}

[source,c]
----
/* init */
cTimestampSlice timestamp_slice_c( int64_t s, cTimestamp const* v );
cTimestampSlice make_timestamp_slice_c( cTimestamp const* beg,
                                        cTimestamp const* end );
cTimestampSlice empty_timestamp_slice_c( void );
/* sub */
cTimestampSlice left_timestamp_slice_c( cTimestampSlice slice, int64_t maxLen );
cTimestampSlice mid_timestamp_slice_c( cTimestampSlice slice, int64_t index );
cTimestampSlice right_timestamp_slice_c( cTimestampSlice slice,
                                         int64_t maxLen );
cTimestampSlice sub_timestamp_slice_c( cTimestampSlice slice,
                                       int64_t begIdx,
                                       int64_t endIdx);
----

[id='cVarTimestampSlice']
==== cVarTimestampSlice
[source,c]
----
struct cVarTimestampSlice
{
int64_t s;
cTimestamp* v;
};
typedef struct cVarTimestampSlice cVarTimestampSlice;
----

{Slice}

[source,c]
----
/* init */
cVarTimestampSlice var_timestamp_slice_c( int64_t s, cTimestamp* v );
cVarTimestampSlice make_var_timestamp_slice_c( cTimestamp* beg,
                                               cTimestamp* end );
cVarTimestampSlice empty_var_timestamp_slice_c( void );
/* sub */
cVarTimestampSlice left_var_timestamp_slice_c( cVarTimestampSlice slice,
                                               int64_t maxLen );
cVarTimestampSlice mid_var_timestamp_slice_c( cVarTimestampSlice slice,
                                              int64_t index );
cVarTimestampSlice right_var_timestamp_slice_c( cVarTimestampSlice slice,
                                                int64_t maxLen );
cVarTimestampSlice sub_var_timestamp_slice_c( cVarTimestampSlice slice,
                                              int64_t begIdx,
                                              int64_t endIdx);
/* var slice */
cVarTimestampSlice as_var_timestamp_slice_c( cVarTimestampSlice slice );
cVarTimestampSlice cast_var_timestamp_slice_c( cVarTimestampSlice slice,
                                               cTimestampSlice sub );
int64_t set_timestamp_slice_c( cVarTimestampSlice dst, cTimestampSlice src );
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ init
=== init

==== now_c
[source,c]
----
cTimestamp now_c( void );
----

Returns the actual moment in time.

==== null_timestamp_c
[source,c]
----
cTimestamp null_timestamp_c( void );
----

Returns an invalid moment in time.

//************************************************************************* cmp
=== cmp

==== cmp_timestamp_c
[source,c]
----
int cmp_timestamp_c( cTimestamp a, cTimestamp b );
----

Compares two timestamps and returns the three possible results:

<0:: if a is earlier as b
0:: if both dates are equal
>0:: if a is later as b

==== eq_timestamp_c
[source,c]
----
bool eq_timestamp_c( cTimestamp a, cTimestamp b );
----

Returns true if both timestamps represent the same moment in time, otherwise
false.

==== timestamp_is_valid_c
[source,c]
----
bool timestamp_is_valid_c( cTimestamp ts );
----

Returns true if the timespan represents a valid moment in time.

//************************************************************************ diff
=== diff

==== between_timestamps_c
[source,c]
----
cDuration between_timestamps_c( cTimestamp a, cTimestamp b );
----

Returns the duration between two timestamps.

==== since_c
[source,c]
----
cDuration since_c( cTimestamp ts );
----

Returns the duration between the timestamp and now.

==== until_c
[source,c]
----
cDuration until_c( cTimestamp ts );
----

Returns the duration between now and the timestamp.
