= cBytes
:xmpldir: {testroot}/clingo/type/cBytes

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

It is recommended to use cBytes and cVarBytes for data buffer.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cBytes']
==== cBytes
:Slice-Type: cByte const
:Slice-Slice: cBytes
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarBytes']
==== cVarBytes
:Slice-Type: cByte
:Slice-Slice: cVarBytes
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

[id='var_bytes_c_']
==== var_bytes_c_
[source,c]
----
#define var_bytes_c_( Size )
----

Macro function that initalizes a cVarBytes that can store Size values.

//************************************************************************* bit
=== bit

==== get_bytes_bit_c
[source,c]
----
cByte get_bytes_bit_c( cBytes slice, int64_t pos );
----

Returns the bit at pos in the byte slice.

.Example
[source,c]
----
include::{xmpldir}/get_bytes_bit.c[]
----

==== set_bytes_bit_c
[source,c]
----
void set_bytes_bit_c( cVarBytes slice, int64_t pos, cByte bit );
----

Sets the bit at pos in the byte slice.

.Example
[source,c]
----
include::{xmpldir}/set_bytes_bit.c[]
----

==== set_bytes_bits_c
[source,c]
----
void set_bytes_bits_c( cVarBytes slice, cRange range, cByte bit );
----

Sets all bits inside the range with the bit value.

.Example
[source,c]
----
include::{xmpldir}/set_bytes_bits.c[]
----

==== set_odd_byte_c
[source,c]
----
void set_odd_byte_c( cVarBytes slice, int64_t pos, int64_t bitOffset, cByte byte );
----

Sets a byte value that overlaps with two bytes in the byte slice.

.Example
[source,c]
----
include::{xmpldir}/set_odd_byte.c[]
----

==== shift_bytes_bits_c
[source,c]
----
void shift_bytes_bits_c( cVarBytes slice, int64_t offset, cByte fillValue );
----

Shifts the bits in a byte slice.
A negative offset shifts the bits to the left, a positive offset shifts the bits
to the right.

.Example
[source,c]
----
include::{xmpldir}/shift_bytes_bits.c[]
----

==== toggle_bytes_bit_c
[source,c]
----
void toggle_bytes_bit_c( cVarBytes slice, int64_t pos );
----

Toggles the bit at pos in the byte slice.

.Example
[source,c]
----
include::{xmpldir}/toggle_bytes_bit.c[]
----

//*********************************************************************** shift
=== shift

==== shift_bytes_c
[source,c]
----
void shift_bytes_c( cVarBytes slice, int64_t offset );
----

Shifts the bits in a byte slice.
A negative offset shifts the bits to the left, a positive offset shifts the bits
to the right.

.Example
[source,c]
----
include::{xmpldir}/shift_bytes.c[]
----

//*********************************************************************** logic
=== logic

==== bitand_bytes_c
[source,c]
----
bool bitand_bytes_c( cBytes a, cBytes b, cVarBytes result );
----

Combines the bits of a and b with a logical and.
Returns false if the slices have different s values.

.Example
[source,c]
----
include::{xmpldir}/bitand_bytes.c[]
----

==== bitor_bytes_c
[source,c]
----
bool bitor_bytes_c( cBytes a, cBytes b, cVarBytes result );
----

Combines the bits of a and b with a logical or.
Returns false if the slices have different s values.

.Example
[source,c]
----
include::{xmpldir}/bitor_bytes.c[]
----

==== compl_bytes_c
[source,c]
----
bool compl_bytes_c( cBytes a, cVarBytes result );
----

Builds the complement of the slice a.
Returns false if the slices have different s values.

.Example
[source,c]
----
include::{xmpldir}/compl_bytes.c[]
----

==== xor_bytes_c
[source,c]
----
bool xor_bytes_c( cBytes a, cBytes b, cVarBytes result );
----

Combine the bits of a and b with a logical xor.
Returns false if the slices have different s values.

.Example
[source,c]
----
include::{xmpldir}/xor_bytes.c[]
----

//************************************************************************ algo
=== algo

==== bytes_ends_with_c
[source,c]
----
bool bytes_ends_with_c( cBytes slice, cBytes needle );
----

{EndsWith}

==== bytes_starts_with_c
[source,c]
----
bool bytes_starts_with_c( cBytes slice, cBytes needle );
----

{StartsWith}

==== cmp_bytes_c
[source,c]
----
#define cmp_bytes_c_( Slice, ... )                                             \
   cmp_bytes_c( (Slice), ((cBytes)slice_c_( cByte, __VA_ARGS__ )) )
int cmp_bytes_c( cBytes a, cBytes b );
----

{CmpSlice}

==== count_eq_byte_c
[source,c]
----
int64_t count_eq_byte_c( cBytes slice, cByte val );
----

{CountEq}

==== find_byte_c
[source,c]
----
cByte const* find_byte_c( cBytes slice, cByte val );
----

{FindVal}

==== index_of_bytes_c
[source,c]
----
int64_t index_of_bytes_c( cBytes slice, cBytes sub );
----

{IndexOfSlice}

==== insert_byte_c
[source,c]
----
int64_t insert_byte_c( cVarBytes slice, int64_t index, cByte val );
----

{InsertVal}

==== insert_bytes_c
[source,c]
----
int64_t insert_bytes_c( cVarBytes dst, int64_t index, cBytes src );
----

{InsertSlice}

==== remove_byte_c
[source,c]
----
bool remove_byte_c( cVarBytes bytes[static 1], int64_t pos );
----

{Remove}

==== take_byte_c
[source,c]
----
bool take_byte_c( cVarBytes bytes[static 1], int64_t pos, cByte val[static 1] );
----

{Take}