= cRange
:xmpldir: {testroot}/clingo/type/cRange

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with cRange values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cRange']
==== cRange
[source,c]
----
struct cRange
{
   int64_t min;
   int64_t max;
};
typedef struct cRange cRange;
----

A cRange is bounded inclusively below and above [min..max].

//******************************************************************* Generated
=== Generated

[id='cRangeSlice']
==== cRangeSlice
[source,c]
----
struct cRangeSlice
{
   int64_t s;
   cRange const* v;
};
typedef struct cRangeSlice cRangeSlice;
----

{Slice}

[id='cVarRangeSlice']
==== cVarRangeSlice
[source,c]
----
struct cVarRangeSlice
{
   int64_t s;
   cRange* v;
};
typedef struct cVarRangeSlice cVarRangeSlice;
----

{Slice}

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ init
=== init

[id='closed_open_range_c_']
==== closed_open_range_c_
[source,c]
----
#define closed_open_range_c_( Start, End )
----

Creates a half opened range [Start..End).

.Example
[source,c]
----
include::{xmpldir}/closed_open_range.c[]
----

[id='closed_range_c_']
==== closed_range_c_
[source,c]
----
#define closed_range_c_( Start, End )
----

Creates a closed range [Start..End].

.Example
[source,c]
----
include::{xmpldir}/closed_range.c[]
----

[id='open_closed_range_c_']
==== open_closed_range_c_
[source,c]
----
#define open_closed_range_c_( Start, End )
----

Creates a half opened range (Start..End].

.Example
[source,c]
----
include::{xmpldir}/open_closed_range.c[]
----

[id='open_range_c_']
==== open_range_c_
[source,c]
----
#define open_range_c_( Start, End )
----

Creates a open range (Start..End).

.Example
[source,c]
----
include::{xmpldir}/open_range.c[]
----

[id='sized_range_c_']
==== sized_range_c_
[source,c]
----
#define sized_range_c_( Start, Size )
----

Creates a range that uses Start as Min Value and contains Size values.

.Example
[source,c]
----
include::{xmpldir}/sized_range.c[]
----

//********************************************************************* overall
=== overall

==== clamp_into_range_c
[source,c]
----
int64_t clamp_into_range_c( cRange range, int64_t value );
----

Clamps the value into the defined range.

.Example
[source,c]
----
include::{xmpldir}/clamp_into_range.c[]
----

==== eq_range_c
[source,c]
----
bool eq_range_c( cRange a, cRange b );
----

Returns true if both ranges are equal, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/eq_range.c[]
----

==== in_range_c
[source,c]
----
bool in_range_c( cRange range, int64_t value );
----

Returns true if the range contains value, otherwise false.

==== range_is_valid_c
[source,c]
----
bool range_is_valid_c( cRange range );
----

Returns true if the range is valid, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/range_is_valid.c[]
----

==== range_size_c
[source,c]
----
int64_t range_size_c( cRange range );
----

Returns the number of values the range contains.

.Example
[source,c]
----
include::{xmpldir}/range_size.c[]
----

==== shift_range_c
[source,c]
----
cRange shift_range_c( cRange range, int64_t distance );
----

Shifts the range forward(positive distance) or backwards(negative distance).

.Example
[source,c]
----
include::{xmpldir}/shift_range.c[]
----
