= cRune
:xmpldir: {testroot}/clingo/type/cRune

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with cRune values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cRune']
==== cRune
[source,c]
----
struct cRune
{
   union
   {
      uint32_t ctrl;
      cByte b[4];
      char c[4];
   };
};
typedef struct cRune cRune;
----

A cRune is a type that can hold a single Unicode code point.
The Unicode code point is encoded in UTF-8 inside a cRune.

==== c_check_rune
[source,c]
----
typedef bool ( *c_check_rune )( cRune r )
----

c_check_rune is the signature of a function to check a rune value.

//******************************************************************* Generated
=== Generated

[id='cRuneSlice]
==== cRuneSlice
:Slice-Type: cRune const
:Slice-Slice: cRuneSlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarRuneSlice']
==== cVarRuneSlice
:Slice-Type: cRune
:Slice-Slice: cVarRuneSlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ utf8
=== utf8

==== is_utf8_head_c
[source,c]
----
bool is_utf8_head_c( char c );
----

Returns true if c is a valid first byte of a UTF-8 encoded code point, otherwise
false.

.Example
[source,c]
----
include::{xmpldir}/is_utf8_head.c[]
----

==== is_utf8_tail_c
[source,c]
----
bool is_utf8_tail_c( char c );
----

Returns true if c is a valid byte in the tail of a UTF-8 encoded code point,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/is_utf8_tail.c[]
----

==== utf8_length_c
[source,c]
----
int8_t utf8_length_c( char c );
----

Returns number of bytes of the UTF-8 encoded code point.
An invalid c value leads to the result 0.

.Example
[source,c]
----
include::{xmpldir}/utf8_length.c[]
----

//*********************************************************************** utf16
=== utf16

==== is_high_utf16_surrogate_c
[source,c]
----
bool is_high_utf16_surrogate_c( uint16_t val );
----

Returns true if the value represents a UTF-16 high surrogate value.

==== is_low_utf16_surrogate_c
[source,c]
----
bool is_low_utf16_surrogate_c( uint16_t val );
----

Returns true if the value represents a UTF-16 low surrogate value.

==== utf16_to_utf32_c
[source,c]
----
uint32_t utf16_to_utf32_c( uint16_t high, uint16_t low );
----

Converts a UTF-16 surrogate pair to an UTF-32 value.

.Example
[source,c]
----
include::{xmpldir}/utf16_to_utf32.c[]
----

==== utf32_to_utf16_c
[source,c]
----
uint16_t utf32_to_utf16_c( uint32_t val, uint16_t low[static 1] );
----

Converts a UTF-32 in to a UTF-16 surrogate pair.
The function returns the high surrogate and writes the low surrogate into low.

.Example
[source,c]
----
include::{xmpldir}/utf32_to_utf16.c[]
----

//************************************************************************ init
=== init

[id='build_rune_c_']
==== build_rune_c_
[source,c]
----
#define build_rune_c_( A, B, C, D )
----

Creates a cRune with the byte values A, B, C and D.

.Example
[source,c]
----
include::{xmpldir}/build_rune.c[]
----

==== make_rune_c
[source,c]
----
cRune make_rune_c( cChars chars );
----

Creates a cRune from the UTF-8 encoded code point at the front.

.Example
[source,c]
----
include::{xmpldir}/make_rune.c[]
----

==== null_rune_c
[source,c]
----
cRune null_rune_c();
----

Creates a invalid cRune.

.Example
[source,c]
----
include::{xmpldir}/null_rune.c[]
----

[id='rune_c']
==== rune_c
[source,c]
----
cRune rune_c( char const cstr[static 1] );
----

Creates a cRune from the UTF-8 encoded code point at the front.

.Example
[source,c]
----
include::{xmpldir}/rune.c[]
----

==== utf16_rune_c
[source,c]
----
cRune utf16_rune_c( uint16_t val );
----

Creates a cRune from a UTF-16 encoded code point.

.Example
[source,c]
----
include::{xmpldir}/utf16_rune.c[]
----

==== utf32_rune_c
[source,c]
----
cRune utf32_rune_c( uint32_t val );
----

Creates a rune from a UTF-32 encoded code point.

.Example
[source,c]
----
include::{xmpldir}/utf32_rune.c[]
----

//********************************************************************* overall
=== overall

==== cmp_rune_c
[source,c]
----
int cmp_rune_c( cRune a, cRune b );
----

Compares the cRune values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_rune.c[]
----

==== eq_rune_c
[source,c]
----
bool eq_rune_c( cRune a, cRune b );
----

Checks if a and b are equal.

.Example
[source,c]
----
include::{xmpldir}/eq_rune.c[]
----

==== rune_code_c
[source,c]
----
uint32_t rune_code_c( cRune r );
----

Converts a rune into a UTF-32 encoded code point.

.Example
[source,c]
----
include::{xmpldir}/rune_code.c[]
----

==== rune_is_c
[source,c]
----
bool rune_is_c( cRune r, char const cstr[static 1] );
----

Checks if r and the first UTF-8 encoded code point in the C string are equal.

.Example
[source,c]
----
include::{xmpldir}/rune_is.c[]
----

==== rune_is_valid_c
[source,c]
----
bool rune_is_valid_c( cRune r );
----

Checks if r contains a valid byte sequence.

.Example
[source,c]
----
include::{xmpldir}/rune_is_valid.c[]
----

==== rune_size_c
[source,c]
----
int8_t rune_size_c( cRune r );
----

Returns how much bytes are used to store the UTF-8 encoded code point.

.Example
[source,c]
----
include::{xmpldir}/rune_size.c[]
----

//******************************************************************* */ access
=== access

==== ceil_to_rune_c
[source,c]
----
char const* ceil_to_rune_c( cChars chars, int64_t index );
----

Returns a pointer to the first char of a UTF-8 encoded code point at the byte
index.
If the char at index is a UTF-8 tail goes the function forward to the next
UTF-8 head.

.Example
[source,c]
----
include::{xmpldir}/ceil_to_rune.c[]
----

==== first_rune_c
[source,c]
----
char const* first_rune_c( cChars chars );
----

Returns a pointer to the first rune in chars.

==== floor_to_rune_c
[source,c]
----
char const* floor_to_rune_c( cChars chars, int64_t index );
----

Returns a pointer to the first char of a UTF-8 encoded code point at the byte
index.
If the char at index is a UTF-8 tail goes the function back to the beginning of
the UTF8- encoded code point.

.Example
[source,c]
----
include::{xmpldir}/floor_to_rune.c[]
----

==== last_rune_c
[source,c]
----
char const* last_rune_c( cChars chars );
----

Returns a pointer to the last rune in chars.

==== nth_rune_c
[source,c]
----
char const* nth_rune_c( cChars chars, int64_t n );
----

Returns a pointer to the nth UTF-8 encoded code point in the chars.
The n value can be nagtive to access the chars backwards.
If n is out of range returns the function NULL.

.Example
[source,c]
----
include::{xmpldir}/nth_rune.c[]
----

//************************************************************************** itr
=== iterate

[id='iterate_runes_c_']
==== iterate_runes_c_
[source,c]
----
#define iterate_runes_c_( Itr, RunePtr, Chars )
----

Macro function to define a for statement to iterate over all runes in chars.

.Example
[source,c]
----
include::{xmpldir}/iterate_runes.c[]
----

==== next_rune_c
[source,c]
----
char const* next_rune_c( cChars chars, char const* itr, cRune r[static 1] )
----

Navigates a to the next UTF-8 encoded code point in a C string.
The returned iterator is invalid if no next value exist.

.Example
[source,c]
----
include::{xmpldir}/next_rune.c[]
----

//*********************************************************************** slice
=== char slice

==== chars_runes_match_c
[source,c]
----
bool chars_runes_match_c( cChars chars, c_check_rune check );
----

Function that returns true when all runes pass the check, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/chars_runes_match.c[]
----

==== count_runes_c
[source,c]
----
int64_t count_runes_c( cChars chars );
----

Counts the number of runes of the chars.
Returns -1 for chars with incomplete runes.

.Example
[source,c]
----
include::{xmpldir}/count_runes.c[]
----

==== fill_rune_slice_c
[source,c]
----
cVarRuneSlice fill_rune_slice_c( cVarRuneSlice dst, cChars src );
----

Fills dst with the complete runes in src.

.Example
[source,c]
----
include::{xmpldir}/fill_rune_slice.c[]
----

==== find_any_rune_c
[source,c]
----
#define find_any_rune_c_( Chars, Cstr )                                        \
   find_any_rune_c( (Chars), c_c( Cstr ) )
char const* find_any_rune_c( cChars chars, cChars set );
----

Returns a pointer to the first char that matches any of the  runes in the set
and NULL if non of the runes exist in the chars.

.Example
[source,c]
----
include::{xmpldir}/find_any_rune.c[]
----

==== find_rune_c
[source,c]
----
#define find_rune_c_( Chars, Cstr )                                            \
   find_rune_c( (Chars), rune_c( Cstr ) )
char const* find_rune_c( cChars chars, cRune r );
----

Returns a pointer to the first char of a UTF-8 encoded code point in a chars
that equals r.

.Example
[source,c]
----
include::{xmpldir}/find_rune.c[]
----

==== find_rune_match_c
[source,c]
----
char const* find_rune_match_c( cChars chars, c_check_rune check );
----

Returns a pointer to the first char of a UTF-8 encoded code point in a chars
that pass the check.

.Example
[source,c]
----
include::{xmpldir}/find_rune_match.c[]
----

==== left_runes_c
[source,c]
----
cChars left_runes_c( cChars chars, int64_t maxLen );
----

Returns the leftmost runes in a chars.
If maxLen is greater or equal the number of runes in the chars returns the
function the whole chars.

.Example
[source,c]
----
include::{xmpldir}/left_runes.c[]
----

==== mid_runes_c
[source,c]
----
cChars mid_runes_c( cChars chars, int64_t index );
----

Returns chars starting(including) at a given rune index.
If index does not point into the chars returns the function an empty slice.

.Example
[source,c]
----
include::{xmpldir}/mid_runes.c[]
----

==== right_runes_c
[source,c]
----
cChars right_runes_c( cChars chars, int64_t maxLen );
----

Returns the rightmost runes in chars.
If maxLen is greater or equal the number of runes in the chars returns the
function the whole chars.

.Example
[source,c]
----
include::{xmpldir}/right_runes.c[]
----

==== sub_runes_c
[source,c]
----
cChars sub_runes_c( cChars chars, int64_t begIdx, int64_t endIdx );
----

The returned chars includes the rune at begIdx(begin index) as first value
and the rune at endIdx-1 as last value.
If begIdx or endIdx are not valid rune indices returns the function a empty
slice.

.Example
[source,c]
----
include::{xmpldir}/sub_runes.c[]
----
