= double
:xmpldir: {testroot}/clingo/type/double

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with float values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cDoubleInfo']
==== cDoubleInfo
[source,c]
----
struct cDoubleInfo
{
   uint8_t sign;
   uint16_t exponent;
   uint64_t mantissa;
};
typedef struct cDoubleInfo cDoubleInfo;
----

cDoubleInfo represents the three sections of a double value.

//******************************************************************* Generated
=== Generated

[id='cDoubleSlice']
==== cDoubleSlice
:Slice-Type: double const
:Slice-Slice: cDoubleSlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarDoubleSlice']
==== cVarDoubleSlice
:Slice-Type: double
:Slice-Slice: cVarDoubleSlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_double_c
[source,c]
----
int cmp_double( double a, double b );
----

Compares two double values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Exampl
[source,c]
----
include::{xmpldir}/cmp_double.c[]
----

[id='double_c_']
==== double_c_
[source,c]
----
#define double_c_( Value )
----

Macro function that casts the Value as double.

==== double_to_float_c
[source,c]
----
bool double_to_float_c( double d, float f[static 1] );
----

{Conv}
Returns true if the double value can be represented in a float variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/double_to_float.c[]
----

==== eq_double_c
[source,c]
----
#define eq_double_c_( D1, D2 )                                                 \
   eq_double_c( (D1), (D2), DBL_EPSILON )
bool eq_double_c( double d1, double d2, double epsilon );
----

Returns true if both value are equal if you allow a epsilon range.

.Example
[source,c]
----
include::{xmpldir}/eq_double.c[]
----

//************************************************************************ info
=== info

==== build_double_c
[source,c]
----
double build_double_c( cDoubleInfo info );
----

Creates a double from a sign, exponent and mantissa value.

.Example
[source,c]
----
include::{xmpldir}/build_double.c[]
----

==== double_info_c
[source,c]
----
cDoubleInfo double_info_c( double d );
----

Splits a double into a sign, exponent and mantissa value.

.Example
[source,c]
----
include::{xmpldir}/double_info.c[]
----

//************************************************************************ swap
=== swap

==== swap_double_c
[source,c]
----
double swap_double_c( double val );
----

{Swap}

==== swap_double_from_c
[source,c]
----
double swap_double_from_c( double val, c_ByteOrder order );
----

{SwapFrom}

==== swap_double_to_c
[source,c]
----
double swap_double_to_c( double val, c_ByteOrder order );
----

{SwapTo}

//************************************************************************ pack
=== pack

==== pack_double_c
[source,c]
----
uint64_t pack_double_c( double d );
----

Packs the bytes of a double in a uint64_t value.

.Example
[source,c]
----
include::{xmpldir}/pack_double.c[]
----

==== unpack_double_c
[source,c]
----
double unpack_double_c( uint64_t u );
----

Unpacks a float from the bytes in a uint64_t value.

.Example
[source,c]
----
include::{xmpldir}/unpack_double.c[]
----

//************************************************************************ algo
=== algo

==== find_double_c
[source,c]
----
double const* find_double_c( cDoubleSlice slice, double d );
----

{FindVal}

==== max_double_c
[source,c]
----
double const* max_double_c( cDoubleSlice slice );
----

{FindMax}

==== min_double_c
[source,c]
----
double const* min_double_c( cDoubleSlice slice );
----

{FindMin}

==== prod_double_c
[source,c]
----
bool prod_double_c( cDoubleSlice slice, double res[static 1] );
----

{Prod}

==== sum_double_c
[source,c]
----
bool sum_double_c( cDoubleSlice slice, double res[static 1] );
----

{Sum}
