= int16
:xmpldir: {testroot}/clingo/type/int16

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with int16_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cInt16s']
==== cInt16s
:Slice-Type: int16_t const
:Slice-Slice: cInt16s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarInt16s']
==== cVarInt16s
:Slice-Type: int16_t
:Slice-Slice: cVarInt16s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_int16_c
[source,c]
----
int cmp_int16_c( int16_t a, int16_t b );
----

Compares two int16_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_int16.c[]
----

[id='int16_c_']
==== int16_c_
[source,c]
----
#define int16_c_( Value )
----

Macro function that casts the Value as int16_t.

//************************************************************************ conv
=== conv

==== int64_to_int16_c
[source,c]
----
bool int64_to_int16_c( int64_t src, int16_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a int16_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_int16.c[]
----

==== uint64_to_int16_c
[source,c]
----
bool uint64_to_int16_c( uint64_t src, int16_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a int16_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int16.c[]
----

//************************************************************************ swap
=== swap

==== swap_int16_c
[source,c]
----
int16_t swap_int16_c( int16_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_int16.c[]
----

==== swap_int16_from_c
[source,c]
----
int16_t swap_int16_from_c( int16_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_int16_from.c[]
----

==== swap_int16_to_c
[source,c]
----
int16_t swap_int16_to_c( int16_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_int16_to.c[]
----

//************************************************************************ algo
=== algo

==== cmp_int16s_c
[source,c]
----
int cmp_int16s_c( cInt16s a, cInt16s b );
----

{CmpSlice}

==== count_eq_int16_c
[source,c]
----
int64_t count_eq_int16_c( cInt16s slice, int16_t val );
----

{CountEq}

==== find_int16_c
[source,c]
----
int16_t const* find_int16_c( cInt16s slice, int16_t val );
----

{FindVal}

==== max_int16_c
[source,c]
----
int16_t const* max_int16_c( cInt16s slice );
----

{FindMax}

==== min_int16_c
[source,c]
----
int16_t const* min_int16_c( cInt16s slice );
----

{FindMin}

==== prod_int16_c
[source,c]
----
bool prod_int16_c( cInt16s slice, int64_t res[static 1] );
----

{Prod}

==== qsort_int16s_c
[source,c]
----
void qsort_int16s_c( cVarInt16s slice );
----

{Qsort}

==== reverse_int16s_c
[source,c]
----
void reverse_int16s_c( cVarInt16s slice );
----

{Reverse}

==== rotate_int16s_c
[source,c]
----
void rotate_int16s_c( cVarInt16s slice, int64_t distance );
----

{Rotate}

==== sum_int16_c
[source,c]
----
bool sum_int16_c( cInt16s slice, int64_t res[static 1] );
----

{Sum}
