= int32
:xmpldir: {testroot}/clingo/type/int32

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with int32_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cInt32s']
==== cInt32s
:Slice-Type: int32_t const
:Slice-Slice: cInt32s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarInt32s']
==== cVarInt32s
:Slice-Type: int32_t
:Slice-Slice: cVarInt32s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_int32_c
[source,c]
----
int cmp_int32_c( int32_t a, int32_t b );
----

Compares two int32_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_int32.c[]
----

[id='int32_c_']
==== int32_c_
[source,c]
----
#define int32_c_( Value )
----

Macro function that casts the Value as int32_t.

//************************************************************************ conv
=== conv

==== int64_to_int32_c
[source,c]
----
bool int64_to_int32_c( int64_t src, int32_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a int32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_int32.c[]
----

==== uint64_to_int32_c
[source,c]
----
bool uint64_to_int32_c( uint64_t src, int32_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a int32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int32.c[]
----

//************************************************************************ swap
=== swap

==== swap_int32_c
[source,c]
----
int32_t swap_int32_c( int32_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_int32.c[]
----

==== swap_int32_from_c
[source,c]
----
int32_t swap_int32_from_c( int32_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_int32_from.c[]
----

==== swap_int32_to_c
[source,c]
----
int32_t swap_int32_to_c( int32_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_int32_to.c[]
----

//************************************************************************ algo
=== algo

==== bsearch_int32_c
[source,c]
----
int32_t const* bsearch_int32_c( cInt32s slice, int32_t val );
----

{Bsearch}

==== cmp_int32s_c
[source,c]
----
int cmp_int32s_c( cInt32s a, cInt32s b );
----

{CmpSlice}

==== count_eq_int32_c
[source,c]
----
int64_t count_eq_int32_c( cInt32s slice, int32_t val );
----

{CountEq}

==== find_int32_c
[source,c]
----
int32_t const* find_int32_c( cInt32s slice, int32_t val );
----

{FindVal}

==== max_int32_c
[source,c]
----
int32_t const* max_int32_c( cInt32s slice );
----

{FindMax}

==== min_int32_c
[source,c]
----
int32_t const* min_int32_c( cInt32s slice );
----

{FindMin}

==== prod_int32_c
[source,c]
----
bool prod_int32_c( cInt32s slice, int64_t res[static 1] );
----

{Prod}

==== qsort_int32s_c
[source,c]
----
void qsort_int32s_c( cVarInt32s slice );
----

{Qsort}

==== remove_int32_c
[source,c]
----
bool remove_int32_c( cVarInt32s slice[static 1], int64_t pos );
----

{Remove}

==== reverse_int32s_c
[source,c]
----
void reverse_int32s_c( cVarInt32s slice );
----

{Reverse}

==== rotate_int32s_c
[source,c]
----
void rotate_int32s_c( cVarInt32s slice, int64_t distance );
----

{Rotate}

==== sum_int32_c
[source,c]
----
bool sum_int32_c( cInt32s slice, int64_t res[static 1] );
----

{Sum}

==== take_int64_c
[source,c]
----
bool take_int32_c( cVarInt32s slice[static 1],
                   int64_t pos,
                   int32_t val[static 1] );
----

{Take}