= int32
:xmpldir: ../../../test/clingo/type/int32

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with int32_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cInt32Slice']
==== cInt32Slice
[source,c]
----
struct cInt32Slice
{
   int64_t s;
   int32_t const* v;
};
typedef struct cInt32Slice cInt32Slice;
----

{Slice}

[source,c]
----
/* init */
cInt32Slice int32_slice_c( int64_t s, int32_t const* v );
cInt32Slice make_int32_slice_c( int32_t const* beg, int32_t const* end );
cInt32Slice empty_int32_slice_c( void );
/* sub */
cInt32Slice left_int32_slice_c( cInt32Slice slice, int64_t maxLen );
cInt32Slice mid_int32_slice_c( cInt32Slice slice, int64_t index );
cInt32Slice right_int32_slice_c( cInt32Slice slice, int64_t maxLen );
cInt32Slice sub_int32_slice_c( cInt32Slice slice,
                               int64_t begIdx,
                               int64_t endIdx );
----

[id='cVarInt32Slice']
==== cVarInt32Slice
[source,c]
----
struct cVarInt32Slice
{
   int64_t s;
   int32_t* v;
};
typedef struct cVarInt32Slice cVarInt32Slice;
----

{Slice}

[source,c]
----
/* init */
cVarInt32Slice var_int32_slice_c( int64_t s, int32_t const* v );
cVarInt32Slice make_var_int32_slice_c( int32_t* beg, int32_t* end );
cVarInt32Slice empty_var_int32_slice_c( void );
/* sub */
cVarInt32Slice left_var_int32_slice_c( cVarInt32Slice slice, int64_t maxLen );
cVarInt32Slice mid_var_int32_slice_c( cVarInt32Slice slice, int64_t index );
cVarInt32Slice right_var_int32_slice_c( cVarInt32Slice slice, int64_t maxLen );
cVarInt32Slice sub_var_int32_slice_c( cVarInt32Slice slice,
                                      int64_t begIdx,
                                      int64_t endIdx );
/* var slice */
cInt32Slice as_int32_slice_c( cVarInt32Slice slice );
cVarInt32Slice cast_int32_slice_c( cVarInt32Slice slice, cInt32Slice sub );
int64_t set_int32_slice_c( cVarInt32Slice dst, cInt32Slice src );
----

[id='cInt32Chunk']
==== cInt32Chunk
[source,c]
----
struct cInt32Chunk
{
   int64_t s;
   int32_t const* v;
   int64_t favSize;
   cInt32Slice slice;
};
typedef struct cInt32Chunk cInt32Chunk;
----

{Chunk}

[source,c]
----
void init_back_int32_chunk_c( cInt32Chunk chunk[static 1],
                              int64_t s,
                              cInt32Slice slice );
void init_front_int32_chunk_c( cInt32Chunk chunk[static 1],
                               int64_t s,
                               cInt32Slice slice );
----

[id='cVarInt32Chunk']
==== cVarInt32Chunk
[source,c]
----
struct cVarInt32Chunk
{
   int64_t s;
   int32_t* v;
   int64_t favSize;
   cInt32Slice slice;
};
typedef struct cVarInt32Chunk cVarInt32Chunk;
----

{Chunk}

[source,c]
----
void init_back_var_int32_chunk_c( cVarInt32Chunk chunk[static 1],
                                  int64_t s,
                                  cVarInt32Slice slice );
void init_front_var_int32_chunk_c( cVarInt32Chunk chunk[static 1],
                                   int64_t s,
                                   cVarInt32Slice slice );
----

[id='cInt32Window']
==== cInt32Window
[source,c]
----
struct cInt32Window
{
   int64_t s;
   int32_t const* v;
   int64_t favSize;
   cInt32Slice slice;
};
typedef struct cInt32Window cInt32Window;
----

{Window}

[source,c]
----
void init_back_int32_window_c( cInt32Window window[static 1],
                               int64_t s,
                               cInt32Slice slice );
void init_front_int32_window_c( cInt32Window window[static 1],
                                int64_t s,
                                cInt32Slice slice );
----

==== cVarInt32Window
[source,c]
----
struct cVarInt32Window
{
   int64_t s;
   int32_t* v;
   int64_t favSize;
   cVarInt32Slice slice;
};
typedef struct cVarInt32Window cVarInt32Window;
----

{Window}

[source,c]
----
void init_back_var_int32_window_c( cVarInt32Window window[static 1],
                                   int64_t s,
                                   cVarInt32Slice slice );
void init_front_var_int32_window_c( cVarInt32Window window[static 1],
                                    int64_t s,
                                    cVarInt32Slice slice );
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_int32_c
[source,c]
----
int cmp_int32_c( int32_t a, int32_t b );
----

Compares two int32_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_int32.c[]
----

[id='int32_c_']
==== int32_c_
[source,c]
----
#define int32_c_( Value )
----

Macro function that casts the Value as int32_t.

//************************************************************************ conv
=== conv

==== int64_to_int32_c
[source,c]
----
bool int64_to_int32_c( int64_t src, int32_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a int32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_int32.c[]
----

==== uint64_to_int32_c
[source,c]
----
bool uint64_to_int32_c( uint64_t src, int32_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a int32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int32.c[]
----

//************************************************************************ swap
=== swap

==== swap_int32_c
[source,c]
----
int32_t swap_int32_c( int32_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_int32.c[]
----

==== swap_int32_from_c
[source,c]
----
int32_t swap_int32_from_c( int32_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_int32_from.c[]
----

==== swap_int32_to_c
[source,c]
----
int32_t swap_int32_to_c( int32_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_int32_to.c[]
----

//************************************************************************ algo
=== algo

==== bsearch_int32_c
[source,c]
----
int32_t const* bsearch_int32_c( cInt32Slice slice, int32_t val );
----

{Bsearch}

==== cmp_int32_slice_c
[source,c]
----
int cmp_int32_slice_c( cInt32Slice a, cInt32Slice b );
----

{CmpSlice}

==== count_eq_int32_c
[source,c]
----
int64_t count_eq_int32_c( cInt32Slice slice, int32_t val );
----

{CountEq}

==== find_int32_c
[source,c]
----
int32_t const* find_int32_c( cInt32Slice slice, int32_t val );
----

{FindVal}

==== max_int32_c
[source,c]
----
int32_t const* max_int32_c( cInt32Slice slice );
----

{FindMax}

==== min_int32_c
[source,c]
----
int32_t const* min_int32_c( cInt32Slice slice );
----

{FindMin}

==== prod_int32_c
[source,c]
----
bool prod_int32_c( cInt32Slice slice, int64_t res[static 1] );
----

{Prod}

==== qsort_int32_slice_c
[source,c]
----
void qsort_int32_slice_c( cVarInt32Slice slice );
----

{Qsort}

==== reverse_int32_slice_c
[source,c]
----
void reverse_int32_slice_c( cVarInt32Slice slice );
----

{Reverse}

==== rotate_int32_slice_c
[source,c]
----
void rotate_int32_slice_c( cVarInt32Slice slice, int64_t distance );
----

{Rotate}

==== sum_int32_c
[source,c]
----
bool sum_int32_c( cInt32Slice slice, int64_t res[static 1] );
----

{Sum}
