= int64
:xmpldir: {testroot}/clingo/type/int64

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Modue with functions and types to work with int64_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cInt64s']
==== cInt64s
:Slice-Type: int64_t const
:Slice-Slice: cInt64s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarInt64s']
==== cVarInt64s
:Slice-Type: int64_t
:Slice-Slice: cVarInt64s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_int64_c
[source,c]
----
int cmp_int64_c( int64_t a, int64_t b );
----

Compares two int64_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_int64.c[]
----

[id='int64_c_']
==== int64_c_
[source,c]
----
#define int64_c_( Value )
----

Macro function that casts the Value as int64_t.

//************************************************************************ conv
=== conv

==== uint64_to_int64_c
[source,c]
----
bool uint64_to_int64_c( uint64_t src, int64_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a int64_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int64.c[]
----

//************************************************************************ swap
=== swap

==== swap_int64_c
[source,c]
----
int64_t swap_int64_c( int64_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_int64.c[]
----

==== swap_int64_from_c
[source,c]
----
int64_t swap_int64_from_c( int64_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_int64_from.c[]
----

==== swap_int64_to_c
[source,c]
----
int64_t swap_int64_to_c( int64_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_int64_to.c[]
----

//************************************************************************ math
=== math

==== hash_int64_c
[source,c]
----
uint64_t hash_int64_c( int64_t val );
----

Returns a hash value of the int64_t value.

==== next_pow2_int64_c
[source,c]
----
int64_t next_pow2_int64_c( int64_t val );
----

Returns the next power of two value.

//************************************************************************ algo
=== algo

==== bsearch_int64_c
[source,c]
----
int64_t const* bsearch_int64_c( cInt64s slice, int64_t val );
----

{Bsearch}

==== cmp_int64s_c
[source,c]
----
int cmp_int64s_c( cInt64s a, cInt64s b );
----

{CmpSlice}

==== count_eq_int64_c
[source,c]
----
int64_t count_eq_int64_c( cInt64s slice, int64_t val );
----

{CountEq}

==== find_int64_c
[source,c]
----
int64_t const* find_int64_c( cInt64s slice, int64_t val );
----

{FindVal}

==== max_int64_c
[source,c]
----
int64_t const* max_int64_c( cInt64s slice );
----

{FindMax}

==== min_int64_c
[source,c]
----
int64_t const* min_int64_c( cInt64s slice );
----

{FindMin}

==== prod_int64_c
[source,c]
----
bool prod_int64_c( cInt64s slice, int64_t res[static 1] );
----

{Prod}

==== qsort_int64s_c
[source,c]
----
void qsort_int64s_c( cVarInt64s slice );
----

{Qsort}

==== remove_int64_c
[source,c]
----
bool remove_int64_c( cVarInt64s slice[static 1], int64_t pos);
----

{Remove}

==== reverse_int64s_c
[source,c]
----
void reverse_int64s_c( cVarInt64s slice );
----

{Reverse}

==== rotate_int64s_c
[source,c]
----
void rotate_int64s_c( cVarInt64s slice, int64_t distance );
----

{Rotate}

==== sum_int64_c
[source,c]
----
bool sum_int64_c( cInt64s slice, int64_t res[static 1] );
----

{Sum}

==== take_int64_c
[source,c]
----
bool take_int64_c( cVarInt64s slice[static 1],
                   int64_t pos,
                   int64_t val[static 1] );
----

{Take}