= int8
:xmpldir: {testroot}/clingo/type/int8

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with int8_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cInt8Slice']
==== cInt8Slice
[source,c]
----
struct cInt8Slice
{
   int64_t s;
   int8_t const* v;
};
typedef struct cInt8Slice cInt8Slice;
----

{Slice}

[id='cVarInt8Slice']
==== cVarInt8Slice
[source,c]
----
struct cVarInt8Slice
{
   int64_t s;
   int8_t* v;
};
typedef struct cVarInt8Slice cVarInt8Slice;
----

{Slice}

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_int8_c
[source,c]
----
int cmp_int8_c( int8_t a, int8_t b );
----

Compares two int8_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_int8.c[]
----

[id='int8_c_']
==== int8_c_
[source,c]
----
#define int8_c_( Value )
----

Macro function that casts the Value as int8_t.

//************************************************************************ conv
=== conv

==== int64_to_int8_c
[source,c]
----
bool int64_to_int8_c( int64_t src, int8_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a int8_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_int8.c[]
----

==== uint64_to_int8_c
[source,c]
----
bool uint64_to_int8_c( uint64_t src, int8_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a int8_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int8.c[]
----

//************************************************************************ algo
=== algo

==== cmp_int8_slice_c
[source,c]
----
int64_t cmp_int8_slice_c( cInt8Slice a, cInt8Slice b );
----

{CmpSlice}

==== count_eq_int8_c
[source,c]
----
int64_t count_eq_int8_c( cInt8Slice slice, int8_t val );
----

{CountEq}

==== find_int8_c
[source,c]
----
int8_t const* find_int8_c( cInt8Slice slice, int8_t val );
----

{FindVal}

==== max_int8_c
[source,c]
----
int8_t const* max_int8_c( cInt8Slice slice );
----

{FindMax}

==== min_int8_c
[source,c]
----
int8_t const* min_int8_c( cInt8Slice slice );
----

{FindMin}

==== prod_int8_c
[source,c]
----
bool prod_int8_c( cInt8Slice slice, int64_t res [static 1] );
----

{Prod}

==== qsort_int8_slice_c
[source,c]
----
void qsort_int8_slice_c( cVarInt8Slice slice );
----

{Qsort}

==== reverse_int8_slice_c
[source,c]
----
void reverse_int8_slice_c( cVarInt8Slice slice );
----

{Reverse}

==== rotate_int8_slice_c
[source,c]
----
void rotate_var_int8_slice_c( cVarInt8Slice slice, int64_t distance );
----

{Rotate}

==== sum_int8_c
[source,c]
----
bool sum_int8_c( cInt8Slice slice, int64_t res[static 1] );
----

{Sum}
