= uint32
:xmpldir: {testroot}/clingo/type/uint32

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with uint32_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cUint32s']
==== cUint32s
:Slice-Type: uint32_t const
:Slice-Slice: cUint32s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarUint32s']
==== cVarUint32s
:Slice-Type: uint32_t
:Slice-Slice: cVarUint32s
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_uint32_c
[source,c]
----
int cmp_uint32_c( uint32_t a, uint32_t b );
----

Compares two uint32_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater to b

.Example
[source,c]
----
include::{xmpldir}/cmp_uint32.c[]
----

[id='uint32_c_']
==== uint32_c_
[source,c]
----
#define uint32_c_( Value )
----

Macro function that casts the Value as uint32_t.

//************************************************************************ conv
=== conv

==== int64_to_uint32_c
[source,c]
----
bool int64_to_uint32_c( int64_t src, uint32_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a uint32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_uint32.c[]
----

==== uint64_to_uint32_c
[source,c]
----
bool uint64_to_uint32_c( uint64_t src, uint32_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a uint32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_uint32.c[]
----

//************************************************************************ swap
=== swap

==== swap_uint32_c
[source,c]
----
uint32_t swap_uint32_c( uint32_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_uint32.c[]
----

==== swap_uint32_from_c
[source,c]
----
uint32_t swap_uint32_from_c( uint32_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_uint32_from.c[]
----

==== swap_uint32_to_c
[source,c]
----
uint32_t swap_uint32_to_c( uint32_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_uint32_to.c[]
----

//************************************************************************ math
=== math

==== next_pow2_uint32_c
[source,c]
----
uint32_t next_pow2_uint32_c( uint32_t val );
----

Smallest power of 2 greater than val.

.Example
[source,c]
----
include::{xmpldir}/next_pow2_uint32.c[]
----

//************************************************************************ algo
=== algo

==== cmp_uint32s_c
[source,c]
----
int cmp_uint32s_c( cUint32s a, cUint32s b );
----

{CmpSlice}

==== count_eq_uint32_c
[source,c]
----
int64_t count_eq_uint32_c( cUint32s slice, uint32_t val );
----

{CountEq}

==== find_uint32_c
[source,c]
----
uint32_t const* find_uint32_c( cUint32s slice, uint32_t val );
----

{FindVal}

==== max_uint32_c
[source,c]
----
uint32_t const* max_uint32_c( cUint32s slice );
----

{FindMax}

==== min_uint32_c
[source,c]
----
uint32_t const* min_uint32_c( cUint32s slice );
----

{FindMin}

==== prod_uint32_c
[source,c]
----
bool prod_uint32_c( cUint32s slice, uint64_t res[static 1] );
----

{Prod}

==== qsort_uint32s_c
[source,c]
----
void qsort_uint32s_c( cVarUint32s slice );
----

{Qsort}

==== reverse_uint32s_c
[source,c]
----
void reverse_uint32s_c( cVarUint32s slice );
----

{Reverse}

==== rotate_uint32s_c
[source,c]
----
void rotate_uint32s_c( cVarUint32s slice, int64_t distance );
----

{Rotate}

==== sum_uint32_c
[source,c]
----
bool sum_uint32_c( cUint32s slice, uint64_t res[static 1] );
----

{Sum}
