= uint32
:xmpldir: ../../../test/clingo/type/uint32

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with uint32_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cUint32Slice']
==== cUint32Slice
[source,c]
----
struct cUint32Slice
{
   int64_t s;
   uint32_t const* v;
};
typedef struct cUint32Slice cUint32Slice;
----

{Slice}

[source,c]
----
/* init */
cUint32Slice uint32_slice_c( int64_t s, uint32_t const* v );
cUint32Slice make_uint32_slice_c( uint32_t const* beg, uint32_t const* end );
cUint32Slice empty_uint32_slice_c( void );
/* sub */
cUint32Slice left_uint32_slice_c( cUint32Slice slice, int64_t maxLen );
cUint32Slice mid_uint32_slice_c( cUint32Slice slice, int64_t index );
cUint32Slice right_uint32_slice_c( cUint32Slice slice, int64_t maxLen );
cUint32Slice sub_uint32_slice_c( cUint32Slice slice,
                                 int64_t begIdx,
                                 int64_t endIdx );
----

[id='cVarUint32Slice']
==== cVarUint32Slice
[source,c]
----
struct cVarUint32Slice
{
   int64_t s;
   uint32_t* v;
};
typedef struct cVarUint32Slice cVarUint32Slice;
----

{Slice}

[source,c]
----
/* init */
cVarUint32Slice var_uint32_slice_c( int64_t s, uint32_t const* v );
cVarUint32Slice make_var_uint32_slice_c( uint32_t* beg, uint32_t* end );
cVarUint32Slice empty_var_uint32_slice_c( void );
/* sub */
cVarUint32Slice left_var_uint32_slice_c( cVarUint32Slice slice, int64_t maxLen );
cVarUint32Slice mid_var_uint32_slice_c( cVarUint32Slice slice, int64_t index );
cVarUint32Slice right_var_uint32_slice_c( cVarUint32Slice slice, int64_t maxLen );
cVarUint32Slice sub_var_uint32_slice_c( cVarUint32Slice slice,
                                        int64_t begIdx,
                                        int64_t endIdx );
/* var slice */
cUint32Slice as_uint32_slice_c( cVarUint32Slice slice );
cVarUint32Slice cast_uint32_slice_c( cVarUint32Slice slice, cUint32Slice sub );
int64_t set_uint32_slice_c( cVarUint32Slice dst, cUint32Slice src );
----

[id='cUint32Chunk']
==== cUint32Chunk
[source,c]
----
struct cUint32Chunk
{
   int64_t s;
   uint32_t const* v;
   int64_t favSize;
   cUint32Slice slice;
};
typedef struct cUint32Chunk cUint32Chunk;
----

{Chunk}

[source,c]
----
void init_back_uint32_chunk_c( cUint32Chunk chunk[static 1],
                               int64_t s,
                               cUint32Slice slice );
void init_front_uint32_chunk_c( cUint32Chunk chunk[static 1],
                                int64_t s,
                                cUint32Slice slice );
----

[id='cVarUint32Chunk']
==== cVarUint32Chunk
[source,c]
----
struct cVarUint32Chunk
{
   int64_t s;
   uint32_t* v;
   int64_t favSize;
   cUint32Slice slice;
};
typedef struct cVarUint32Chunk cVarUint32Chunk;
----

{Chunk}

[source,c]
----
void init_back_var_uint32_chunk_c( cVarUint32Chunk chunk[static 1],
                                   int64_t s,
                                   cVarUint32Slice slice );
void init_front_var_uint32_chunk_c( cVarUint32Chunk chunk[static 1],
                                    int64_t s,
                                    cVarUint32Slice slice );
----

[id='cUint32Window']
==== cUint32Window
[source,c]
----
struct cUint32Window
{
   int64_t s;
   uint32_t const* v;
   int64_t favSize;
   cUint32Slice slice;
};
typedef struct cUint32Window cUint32Window;
----

{Window}

[source,c]
----
void init_back_uint32_window_c( cUint32Window window[static 1],
                                int64_t s,
                                cUint32Slice slice );
void init_front_uint32_window_c( cUint32Window window[static 1],
                                 int64_t s,
                                 cUint32Slice slice );
----

[id='cVarUint32Window']
==== cVarUint32Window
[source,c]
----
struct cVarUint32Window
{
   int64_t s;
   uint32_t* v;
   int64_t favSize;
   cVarUint32Slice slice;
};
typedef struct cVarUint32Window cVarUint32Window;
----

{Window}

[source,c]
----
void init_back_var_uint32_window_c( cVarUint32Window window[static 1],
                                    int64_t s,
                                    cVarUint32Slice slice );
void init_front_var_uint32_window_c( cVarUint32Window window[static 1],
                                     int64_t s,
                                     cVarUint32Slice slice );
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_uint32_c
[source,c]
----
int cmp_uint32_c( uint32_t a, uint32_t b );
----

Compares two uint32_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater to b

.Example
[source,c]
----
include::{xmpldir}/cmp_uint32.c[]
----

[id='uint32_c_']
==== uint32_c_
[source,c]
----
#define uint32_c_( Value )
----

Macro function that casts the Value as uint32_t.

//************************************************************************ conv
=== conv

==== int64_to_uint32_c
[source,c]
----
bool int64_to_uint32_c( int64_t src, uint32_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a uint32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_uint32.c[]
----

==== uint64_to_uint32_c
[source,c]
----
bool uint64_to_uint32_c( uint64_t src, uint32_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a uint32_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_uint32.c[]
----

//************************************************************************ swap
=== swap

==== swap_uint32_c
[source,c]
----
uint32_t swap_uint32_c( uint32_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_uint32.c[]
----

==== swap_uint32_from_c
[source,c]
----
uint32_t swap_uint32_from_c( uint32_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_uint32_from.c[]
----

==== swap_uint32_to_c
[source,c]
----
uint32_t swap_uint32_to_c( uint32_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_uint32_to.c[]
----

//************************************************************************ math
=== math

==== next_pow2_uint32_c
[source,c]
----
uint32_t next_pow2_uint32_c( uint32_t val );
----

Smallest power of 2 greater than val.

.Example
[source,c]
----
include::{xmpldir}/next_pow2_uint32.c[]
----

//************************************************************************ algo
=== algo

==== cmp_uint32_slice_c
[source,c]
----
int cmp_uint32_slice_c( cUint32Slice a, cUint32Slice b );
----

{CmpSlice}

==== count_eq_uint32_c
[source,c]
----
int64_t count_eq_uint32_c( cUint32Slice slice, uint32_t val );
----

{CountEq}

==== find_uint32_c
[source,c]
----
uint32_t const* find_uint32_c( cUint32Slice slice, uint32_t val );
----

{FindVal}

==== max_uint32_c
[source,c]
----
uint32_t const* max_uint32_c( cUint32Slice slice );
----

{FindMax}

==== min_uint32_c
[source,c]
----
uint32_t const* min_uint32_c( cUint32Slice slice );
----

{FindMin}

==== prod_uint32_c
[source,c]
----
bool prod_uint32_c( cUint32Slice slice, uint64_t res[static 1] );
----

{Prod}

==== qsort_uint32_slice_c
[source,c]
----
void qsort_uint32_slice_c( cVarUint32Slice slice );
----

{Qsort}

==== reverse_uint32_slice_c
[source,c]
----
void reverse_uint32_slice_c( cVarUint32Slice slice );
----

{Reverse}

==== rotate_uint32_slice_c
[source,c]
----
void rotate_uint32_slice_c( cVarUint32Slice slice, int64_t distance );
----

{Rotate}

==== sum_uint32_c
[source,c]
----
bool sum_uint32_c( cUint32Slice slice, uint64_t res[static 1] );
----

{Sum}
