= uint64
:xmpldir: {testroot}/clingo/type/uint64

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with uint64_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cUint64Slice']
==== cUint64Slice
:Slice-Type: uint64_t const
:Slice-Slice: cUint64Slice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarUint64Slice']
==== cVarUint64Slice
:Slice-Type: uint64_t
:Slice-Slice: cVarUint64Slice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== build_uint64_c_
[source,c]
----
#define build_uint64_c_( a, b )
----

Macro function that builds a uint64_t value by concatenating two uint32_t
values.

.Example
[source,c]
----
include::{xmpldir}/build_uint64.c[]
----

==== cmp_uint64_c
[source,c]
----
int cmp_uint64_c( uint64_t a, uint64_t b );
----

Compares two uint64_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater to b

.Example
[source,c]
----
include::{xmpldir}/cmp_uint64.c[]
----

[id='uint64_c_']
==== uint64_c_
[source,c]
----
#define uint64_c_( Value )
----

Macro function that casts the Value as uint64_t.

//************************************************************************ conv
=== conv

==== int64_to_uint64_c
[source,c]
----
bool int64_to_uint64_c( int64_t src, uint64_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a uint64_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_uint64.c[]
----

//************************************************************************ swap
=== swap

==== swap_uint64_c
[source,c]
----
uint64_t swap_uint64_c( uint64_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_uint64.c[]
----

==== swap_uint64_from_c
[source,c]
----
uint64_t swap_uint64_from_c( uint64_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_uint64_from.c[]
----

==== swap_uint64_to_c
[source,c]
----
uint64_t swap_uint64_to_c( uint64_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_uint64_to.c[]
----

//************************************************************************ math
=== math

==== is_pow2_uint64_c
[source,c]
----
bool is_pow2_uint64_c( uint64_t val );
----

Check that returns true if val is an integral power of two, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/is_pow2_uint64.c[]
----

==== next_pow2_uint64_c
[source,c]
----
uint64_t next_pow2_uint64_c( uint64_t val );
----

Smallest power of 2 greater than val.

.Example
[source,c]
----
include::{xmpldir}/next_pow2_uint64.c[]
----

==== log2_uint64_c
[source,c]
----
uint8_t log2_uint64_c( uint64_t val );
----

Returns the binary (base-2) logarithm of val.

.Example
[source,c]
----
include::{xmpldir}/log2_uint64.c[]
----

//************************************************************************ algo
=== algo

==== cmp_uint64_slice_c
[source,c]
----
int cmp_uint64_slice_c( cUint64Slice a, cUint64Slice b );
----

{CmpSlice}

==== count_eq_uint64_c
[source,c]
----
int64_t count_eq_uint64_c( cUint64Slice slice, uint64_t val );
----

{CountEq}

==== find_uint64_c
[source,c]
----
uint64_t const* find_uint64_c( cUint64Slice slice, uint64_t val );
----

{FindVal}

==== max_uint64_c
[source,c]
----
uint64_t const* max_uint64_c( cUint64Slice slice );
----

{FindMax}

==== min_uint64_c
[source,c]
----
uint64_t const* min_uint64_c( cUint64Slice slice );
----

{FindMin}

==== prod_uint64_c
[source,c]
----
bool prod_uint64_c( cUint64Slice slice, uint64_t res[static 1] );
----

{Prod}

==== qsort_uint64_slice_c
[source,c]
----
void qsort_uint64_slice_c( cVarUint64Slice slice );
----

{Qsort}

==== reverse_uint64_slice_c
[source,c]
----
void reverse_uint64_slice_c( cVarUint64Slice slice );
----

{Reverse}

==== rotate_uint64_slice_c
[source,c]
----
void rotate_uint64_slice_c( cVarUint64Slice slice, int64_t distance );
----

{Rotate}

==== sum_uint64_c
[source,c]
----
bool sum_uint64_c( cUint64Slice slice, uint64_t res[static 1] );
----

{Sum}
