= uint8
:xmpldir: {testroot}/clingo/type/uint8

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with uint8_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cUint8Slice']
==== cUint8Slice
[source,c]
----
struct cUint8Slice
{
   int64_t s;
   uint8_t const* v;
};
typedef struct cUint8Slice cUint8Slice;
----

{Slice}

[id='cVarUint8Slice']
==== cVarUint8Slice
[source,c]
----
struct cVarUint8Slice
{
   int64_t s;
   uint8_t* v;
};
typedef struct cVarUint8Slice cVarUint8Slice;
----

{Slice}

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_uint8_c
[source,c]
----
int cmp_uint8_c( uint8_t a, uint8_t b );
----

Compares two uint8_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_uint8.c[]
----

==== uint8_c_
[source,c]
----
#define uint8_c_( Value )
----

Macro function that casts the Value as uint8_t.

//************************************************************************ conv
=== conv

==== int64_to_uint8_c
[source,c]
----
bool int64_to_uint8_c( int64_t src, uint8_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a uint8_t variable,
ohterwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_uint8.c[]
----

==== uint64_to_uint8_c
[source,c]
----
bool uint64_to_uint8_c( uint64_t src, uint8_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a uint8_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int8.c[]
----

//************************************************************************ algo
=== algo

==== cmp_uint8_slice_c
[source,c]
----
int cmp_uint8_slice_c( cUint8Slice a, cUint8Slice b );
----

{CmpSlice}

==== count_eq_uint8_c
[source,c]
----
int64_t count_eq_uint8_c( cUint8Slice slice, uint8_t val );
----

{CountEq}

==== find_uint8_c
[source,c]
----
uint8_t const* find_uint8_c( cUint8Slice slice, uint8_t val );
----

{FindVal}

==== max_uint8_c
[source,c]
----
uint8_t const* max_uint8_c( cUint8Slice slice );
----

{FindMax}

==== min_uint8_c
[source,c]
----
uint8_t const* min_uint8_c( cUint8Slice slice );
----

{FindMin}

==== prod_uint8_c
[source,c]
----
bool prod_uint8_c( cUint8Slice slice, uint64_t res[static 1] );
----

{Prod}

==== qsort_uint8_slice_c
[source,c]
----
void qsort_uint8_slice_c( cVarUint8Slice slice );
----

{Qsort}

==== reverse_uint8_slice_c
[source,c]
----
void reverse_uint8_slice_c( cVarUint8Slice slice );
----

{Reverse}

==== rotate_uint8_slice_c
[source,c]
----
void rotate_uint8_slice_c( cVarUint8Slice slice, int64_t distance );
----

{Rotate}

==== sum_uint8_c
[source,c]
----
bool sum_uint8_c( cUint8Slice slice, uint64_t res[static 1] );
----

{Sum}
