= uint16
:xmpldir: {testroot}/clingo/type/uint16

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with uint16_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cUint16Slice']
==== cUint16Slice
:Slice-Type: uint16_t const
:Slice-Slice: cUint16Slice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarUint16Slice']
==== cVarUint16Slice
:Slice-Type: uint16_t
:Slice-Slice: cVarUint16Slice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_uint16_c
[source,c]
----
int cmp_uint16_c( uint16_t a, uint16_t b );
----

Compares two uint16_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_uint16.c[]
----

[id='uint16_c_']
==== uint16_c_
[source,c]
----
#define uint16_c_( Value )
----

Macro function that casts the Value as uint16_t.

//************************************************************************ conv
=== conv

==== int64_to_uint16_c
[source,c]
----
bool int64_to_uint16_c( int64_t src, uint16_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a uint16_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_uint16.c[]
----

==== uint64_to_uint16_c
[source,c]
----
bool uint64_to_uint16_c( uint64_t src, uint16_t dst[static 1] );
----

{Conv}
Returns true if the uint16_t value can be represented in a uint16_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_uint16.c[]
----

//************************************************************************ swap
=== swap

==== swap_uint16_c
[source,c]
----
uint16_t swap_uint16_c( uint16_t val );
----

{Swap}

.Example
[source,c]
----
include::{xmpldir}/swap_uint16.c[]
----

==== swap_uint16_from_c
[source,c]
----
uint16_t swap_uint16_from_c( uint16_t val, c_ByteOrder order );
----

{SwapFrom}

.Example
[source,c]
----
include::{xmpldir}/swap_uint16_from.c[]
----

==== swap_uint16_to_c
[source,c]
----
uint16_t swap_uint16_to_c( uint16_t val, c_ByteOrder order );
----

{SwapTo}

.Example
[source,c]
----
include::{xmpldir}/swap_uint16_to.c[]
----

//************************************************************************ algo
=== algo

==== cmp_uint16_slice_c
[source,c]
----
int cmp_uint16_slice_c( cUint16Slice a, cUint16Slice b );
----

{CmpSlice}

==== count_eq_uint16_c
[source,c]
----
int64_t count_eq_uint16_c( cUint16Slice slice, uint16_t val );
----

{CountEq}

==== find_uint16_c
[source,c]
----
uint16_t const* find_uint16_c( cUint16Slice slice, uint16_t val );
----

{FindVal}

==== max_uint16_c
[source,c]
----
uint16_t const* max_uint16_c( cUint16Slice slice );
----

{FindMax}

==== min_uint16_c
[source,c]
----
uint16_t const* min_uint16_c( cUint16Slice slice );
----

{FindMin}

==== prod_uint16_c
[source,c]
----
bool prod_uint16_c( cUint16Slice slice, uint64_t res[static 1] );
----

{Prod}

==== qsort_uint16_slice_c
[source,c]
----
void qsort_uint16_slice_c( cVarUint16Slice slice );
----

{Qsort}

==== reverse_uint16_slice_c
[source,c]
----
void reverse_uint16_slice_c( cVarUint16Slice slice );
----

{Reverse}

==== rotate_uint16_slice_c
[source,c]
----
void rotate_uint16_slice_c( cVarUint16Slice slice, int64_t distance );
----

{Rotate}

==== sum_uint16_c
[source,c]
----
bool sum_uint16_c( cUint16Slice slice, uint64_t res[static 1] );
----

{Sum}
