= uint8
:xmpldir: ../../../test/clingo/type/uint8

include::_attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module with functions and types to work with uint8_t values.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='cUint8Slice']
==== cUint8Slice
[source,c]
----
struct cUint8Slice
{
   int64_t s;
   uint8_t const* v;
};
typedef struct cUint8Slice cUint8Slice;
----

{Slice}

[source,c]
----
/* init */
cUint8Slice uint8_slice_c( int64_t s, uint8_t const* v );
cUint8Slice make_uint8_slice_c( uint8_t const* beg, uint8_t const* end );
cUint8Slice empty_uint8_slice_c( void );
/* sub */
cUint8Slice left_uint8_slice_c( cUint8Slice slice, int64_t maxLen );
cUint8Slice mid_uint8_slice_c( cUint8Slice slice, int64_t index );
cUint8Slice right_uint8_slice_c( cUint8Slice slice, int64_t maxLen );
cUint8Slice sub_uint8_slice_c( cUint8Slice slice,
                               int64_t begIdx,
                               int64_t endIdx );
----

[id='cVarUint8Slice']
==== cVarUint8Slice
[source,c]
----
struct cVarUint8Slice
{
   int64_t s;
   uint8_t* v;
};
typedef struct cVarUint8Slice cVarUint8Slice;
----

{Slice}

[source,c]
----
/* init */
cVarUint8Slice var_uint8_slice_c( int64_t s, uint8_t const* v );
cVarUint8Slice make_var_uint8_slice_c( uint8_t* beg, uint8_t* end );
cVarUint8Slice empty_var_uint8_slice_c( void );
/* sub */
cVarUint8Slice left_var_uint8_slice_c( cVarUint8Slice slice, int64_t maxLen );
cVarUint8Slice mid_var_uint8_slice_c( cVarUint8Slice slice, int64_t index );
cVarUint8Slice right_var_uint8_slice_c( cVarUint8Slice slice, int64_t maxLen );
cVarUint8Slice sub_var_uint8_slice_c( cVarUint8Slice slice,
                                      int64_t begIdx,
                                      int64_t endIdx );
/* var slice */
cUint8Slice as_uint8_slice_c( cVarUint8Slice slice );
cVarUint8Slice cast_uint8_slice_c( cVarUint8Slice slice, cUint8Slice sub );
int64_t set_uint8_slice_c( cVarUint8Slice dst, cUint8Slice src );
----

[id='cUint8Chunk']
==== cUint8Chunk
[source,c]
----
struct cUint8Chunk
{
   int64_t s;
   uint8_t const* v;
   int64_t favSize;
   cUint8Slice slice;
};
typedef struct cUint8Chunk cUint8Chunk;
----

{Chunk}

[source,c]
----
void init_back_uint8_chunk_c( cUint8Chunk chunk[static 1],
                              int64_t s,
                              cUint8Slice slice );
void init_front_uint8_chunk_c( cUint8Chunk chunk[static 1],
                               int64_t s,
                               cUint8Slice slice );
----

[id='cVarUint8Chunk']
==== cVarUint8Chunk
[source,c]
----
struct cVarUint8Chunk
{
   int64_t s;
   uint8_t* v;
   int64_t favSize;
   cUint8Slice slice;
};
typedef struct cVarUint8Chunk cVarUint8Chunk;
----

{Chunk}

[source,c]
----
void init_back_var_uint8_chunk_c( cVarUint8Chunk chunk[static 1],
                                  int64_t s,
                                  cVarUint8Slice slice );
void init_front_var_uint8_chunk_c( cVarUint8Chunk chunk[static 1],
                                   int64_t s,
                                   cVarUint8Slice slice );
----

[id='cUint8Window']
==== cUint8Window
[source,c]
----
struct cUint8Window
{
   int64_t s;
   uint8_t const* v;
   int64_t favSize;
   cUint8Slice slice;
};
typedef struct cUint8Window cUint8Window;
----

{Window}

[source,c]
----
void init_back_uint8_window_c( cUint8Window window[static 1],
                               int64_t s,
                               cUint8Slice slice );
void init_front_uint8_window_c( cUint8Window window[static 1],
                                int64_t s,
                                cUint8Slice slice );
----

[id='cVarUint8Window']
==== cVarUint8Window
[source,c]
----
struct cVarUint8Window
{
   int64_t s;
   uint8_t* v;
   int64_t favSize;
   cVarUint8Slice slice;
};
typedef struct cVarUint8Window cVarUint8Window;
----

{Window}

[source,c]
----
void init_back_var_uint8_window_c( cVarUint8Window window[static 1],
                                   int64_t s,
                                   cVarUint8Slice slice );
void init_front_var_uint8_window_c( cVarUint8Window window[static 1],
                                    int64_t s,
                                    cVarUint8Slice slice );
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************* overall
=== overall

==== cmp_uint8_c
[source,c]
----
int cmp_uint8_c( uint8_t a, uint8_t b );
----

Compares two uint8_t values and returns the three possible results:

<0:: means that a is less compared to b
0:: means that a and b are equal
>0:: means that a is greater compared to b

.Example
[source,c]
----
include::{xmpldir}/cmp_uint8.c[]
----

==== uint8_c_
[source,c]
----
#define uint8_c_( Value )
----

Macro function that casts the Value as uint8_t.

//************************************************************************ conv
=== conv

==== int64_to_uint8_c
[source,c]
----
bool int64_to_uint8_c( int64_t src, uint8_t dst[static 1] );
----

{Conv}
Returns true if the int64_t value can be represented in a uint8_t variable,
ohterwise false.

.Example
[source,c]
----
include::{xmpldir}/int64_to_uint8.c[]
----

==== uint64_to_uint8_c
[source,c]
----
bool uint64_to_uint8_c( uint64_t src, uint8_t dst[static 1] );
----

{Conv}
Returns true if the uint64_t value can be represented in a uint8_t variable,
otherwise false.

.Example
[source,c]
----
include::{xmpldir}/uint64_to_int8.c[]
----

//************************************************************************ algo
=== algo

==== cmp_uint8_slice_c
[source,c]
----
int cmp_uint8_slice_c( cUint8Slice a, cUint8Slice b );
----

{CmpSlice}

==== count_eq_uint8_c
[source,c]
----
int64_t count_eq_uint8_c( cUint8Slice slice, uint8_t val );
----

{CountEq}

==== find_uint8_c
[source,c]
----
uint8_t const* find_uint8_c( cUint8Slice slice, uint8_t val );
----

{FindVal}

==== max_uint8_c
[source,c]
----
uint8_t const* max_uint8_c( cUint8Slice slice );
----

{FindMax}

==== min_uint8_c
[source,c]
----
uint8_t const* min_uint8_c( cUint8Slice slice );
----

{FindMin}

==== prod_uint8_c
[source,c]
----
bool prod_uint8_c( cUint8Slice slice, uint64_t res[static 1] );
----

{Prod}

==== qsort_uint8_slice_c
[source,c]
----
void qsort_uint8_slice_c( cVarUint8Slice slice );
----

{Qsort}

==== reverse_uint8_slice_c
[source,c]
----
void reverse_uint8_slice_c( cVarUint8Slice slice );
----

{Reverse}

==== rotate_uint8_slice_c
[source,c]
----
void rotate_uint8_slice_c( cVarUint8Slice slice, int64_t distance );
----

{Rotate}

==== sum_uint8_c
[source,c]
----
bool sum_uint8_c( cUint8Slice slice, uint64_t res[static 1] );
----

{Sum}
