local doctree = {
   [ "clingo" ] = {
      [ "color" ] = {
         "cCmyk.adoc",
         "cCmyk32.adoc",
         "cColor.adoc",
         "cHsl.adoc",
         "cHsv.adoc",
         "cP3Creator.adoc",
         "cRgb.adoc",
         "cRgb24.adoc",
         "image.adoc",
      },
      [ "container" ] = {
         "CBitVec.adoc",
         "CByteVec.adoc",
         "CInt64Map.adoc",
         "CInt64Set.adoc",
         "CInt64Vec.adoc",
         "CObjectVec.adoc",
         "map.adoc",
         "set.adoc",
         "vec.adoc",
      },
      [ "io" ] = {
         "cCell.adoc",
         "cRecorder.adoc",
         "cScanner.adoc",
         "FILE.adoc",
         "jot.adoc",
         "print.adoc",
         "read.adoc",
         "read_type.adoc",
         "write.adoc",
         "write_type.adoc",
      },
      [ "lang" ] = {
         "algo.adoc",
         "benchmark.adoc",
         "chunk.adoc",
         "CObject.adoc",
         "error.adoc",
         "expect.adoc",
         "func.adoc",
         "locale.adoc",
         "math.adoc",
         "mem.adoc",
         "slice.adoc",
         "window.adoc",
      },
      [ "string" ] = {
         "CDictionary.adoc",
         "CString.adoc",
         "CStringBuilder.adoc",
         "CStringList.adoc",
         "CStringSet.adoc",
      },
      [ "time" ] = {
         "c_Month.adoc",
         "C_TimeFormats.adoc",
         "c_WeekDay.adoc",
         "cDate.adoc",
         "cDatePeriod.adoc",
         "CDaySet.adoc",
         "cDaytime.adoc",
         "cDuration.adoc",
         "cHmsn.adoc",
         "cMonthDay.adoc",
         "cOrdinalDate.adoc",
         "cStopwatch.adoc",
         "cTime.adoc",
         "cTimestamp.adoc",
         "cTzOffset.adoc",
         "cWeekDate.adoc",
         "cYmd.adoc",
         "year.adoc",
      },
      [ "type" ] = {
         "bool.adoc",
         "c_ByteOrder.adoc",
         "cByte.adoc",
         "cBytes.adoc",
         "cChars.adoc",
         "cCharsSlice.adoc",
         "cCharsToken.adoc",
         "char.adoc",
         "cRange.adoc",
         "cRune.adoc",
         "cRuneRange.adoc",
         "double.adoc",
         "float.adoc",
         "int16.adoc",
         "int32.adoc",
         "int64.adoc",
         "int8.adoc",
         "uint16.adoc",
         "uint32.adoc",
         "uint64.adoc",
         "uint8.adoc",
      },
   }
}

return doctree
