= set
:xmpldir: {testroot}/clingo/container/set

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that defines the macros to generate set types.

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Type and Definitions

[id='cSetInfo']
==== cSetInfo
[source,c]
----
struct cSetItr
{
   int64_t count;
   int64_t size;
   float maxLoad;
};
typedef struct cSetItr cSetItr;
----

cSetInfo stores the properties of the set.
The count value tells how much elements are stored in the set.
The size shows how much memory is allocated, the maxLoad says how much percent
of the size can be used without to grow.

[id='cSetItr']
==== cSetItr
[source,c]
----
typedef struct
{
   int64_t _v;
} cSetItr;
----

Struct to iterate over the entries in a set.

//******************************************************************************
//****************************************************** Code Generation Macros
//******************************************************************************
[id='Code-Generation-Macros']
== Code Generation Macros

//********************************************************************* iterate

[id='NEXT_IN_SET_C_']
==== NEXT_IN_SET_C_
[source,c]
----
#define NEXT_IN_SET_C_(                                                        \
   FuncSuffix, SetType, RowType, ValType, DoRefVal                             \
)
----

Generates a function that gets a pointer to the next value in the set after the 
iterator position.
The generated function has the following common signatures:
[source,c]
----
cSetItr next_in_FuncSuffix( SetTyoe const* set,
                            cSetItr itr,
                            ValType const* val[static 1] );
)
----

The function gives only read access to the value.
The returned iterator is invalid if no next value exist.

//************************************************************************ type
[id='SET_STRUCTS_C_']
==== SET_STRUCTS_C_
[source,c]
----
#define SET_STRUCTS_C_(                                                        \
   SetType, RowType, ValType                                                   \
)
----

Generates the structs that all functions in this module use.

[source,c]
----
struct RowType                                                                 \
{                                                                              \
   int32_t dist;                                                               \
   union                                                                       \
   {                                                                           \
      ValType k;                                                               \
      ValType v;                                                               \
   };                                                                          \
};                                                                             \
typedef struct RowType RowType;                                                \
                                                                               \
struct SetType                                                                 \
{                                                                              \
   RowType* array;                                                             \
   uint8_t shift;                                                              \
   cSetInfo i;                                                                 \
};                                                                             \
typedef struct SetType SetType;
----

[id='OBJ_SET_DEF_C_']
==== OBJ_SET_DEF_C_
[source,c]
----
#define OBJ_SET_DEF_C_(                                                        \
   SetType, ObjType, FuncSuffix, Meta                                          \
)
----

Generates the definition of a set to store objects from type ObjType for a .h
file.

[source,c]
----
struct SetType;
typedef struct SetType SetType;
extern cMeta const Meta;
/**************************************/
SetType* make_FuncSuffix( int64_t size, float maxLoad );
SetType* new_FuncSuffix();
/**************************************/
cSetInfo const* info_of_##FuncSuffix( SetType const* set );
bool resize_FuncSuffix( SetType* set, int64_t size );
bool set_max_load_of_FuncSuffix( SetType* set, float maxLoad );
/**************************************/
bool in_FuncSuffix( SetType const* set, ObjType const* obj );
cSetItr next_in_FuncSuffix( SetType const* set,
                            cSetItr itr,
                            ObjType const* obj[static 1] );
bool remove_from_FuncSuffix( SetType* set, ObjType const* obj );
bool set_on_FuncSuffix( SetType* set, ObjType* obj );
----

[id='OBJ_SET_IMPL_C_']
==== OBJ_SET_IMPL_C_
[source,c]
----
#define OBJ_OBJ_MAP_IMPL_C_(                                                   \
   Static, SetType, RowType, ObjType, FuncSuffix, Meta, HashFunc, CmpFunc      \
)
----

Generates the implementation of a set to store objects from type ObjType for
a .c file.
The Static value can be used to define the visibility of the functions.

[source,c]
----
struct SetType;
typedef struct SetType SetType;
struct RowType;
typedef RowType RowType;
extern cMeta const Meta;
/**************************************/
SetType* make_FuncSuffix( int64_t size, float maxLoad );
SetType* new_FuncSuffix();
/**************************************/
cSetInfo const* info_of_##FuncSuffix( SetType const* set );
bool resize_FuncSuffix( SetType* set, int64_t size );
bool set_max_load_of_FuncSuffix( SetType* set, float maxLoad );
/**************************************/
bool in_FuncSuffix( SetType const* set, ObjType const* obj );
cSetItr next_in_FuncSuffix( SetType const* set,
                            cSetItr itr,
                            ObjType const* obj[static 1] );
bool remove_from_FuncSuffix( SetType* set, ObjType const* obj );
bool set_on_FuncSuffix( SetType* set, ObjType* obj );
/**************************************/
bool intl_erase_in_FuncSuffix( SetType* set, int64_t index, RowType* oldRow );
int64_t intl_index_in_FuncSuffix( SetType* set, uint64_t hash, KeyType key );
bool intl_set_on_FuncSuffix( SetType* set,
                             uint64_t hash,
                             RowType* row,
                             RowType* out );
----

[id='VAL_SET_DEF_C_']
==== VAL_SET_DEF_C_
[source,c]
----
#define VAL_SET_DEF_C_(                                                        \
   SetType, ValType, FuncSuffix, Meta                                          \
)
----

Generates the definition of a set to store values from type ValType for a .h
file.

[source,c]
----
struct SetType;
typedef struct SetType SetType;
extern cMeta const Meta;
/**************************************/
SetType* make_FuncSuffix( int64_t size, float maxLoad );
SetType* new_FuncSuffix();
/**************************************/
cSetInfo const* info_of_FuncSuffx( SetType const* set );
bool resize_FuncSuffix( SetType* set, int64_t size );
bool set_max_load_of_FuncSuffix( SetType* set, float maxLoad );
/**************************************/
bool in_FuncSuffix( SetType const* set, ValType val );
cSetItr next_in_FuncSuffix( SetType const* set,
                            cSetItr itr,
                            ValType const* val[static 1] );
bool remove_from_FuncSuffix( SetType* set, ValType val );
bool set_on_FuncSuffix( SetType* set, ValType val );
----

[id='VAL_SET_IMPL_C_']
==== VAL_SET_IMPL_C_
[source,c]
----
#define VAL_SET_IMPL_C_(                                                       \
   Static, SetType, RowType, ValType,                                          \
   FuncSuffix, Meta, HashFunc, CmpFunc, DoRef                                  \
)
----

Generates the implementation of a set to store values from type ValType for
a .c file.
The Static value can be used to define the visibility of the functions.

[source,c]
----
struct SetType;
typedef struct SetType SetType;
struct RowType;
typedef struct RowType RowType;
extern cMeta const Meta;
/**************************************/
SetType* make_FuncSuffix( int64_t size, float maxLoad );
SetType* new_FuncSuffix();
/**************************************/
cSetInfo const* info_of_FuncSuffx( SetType const* set );
bool resize_FuncSuffix( SetType* set, int64_t size );
bool set_max_load_of_FuncSuffix( SetType* set, float maxLoad );
/**************************************/
bool in_FuncSuffix( SetType const* set, ValType val );
cSetItr next_in_FuncSuffix( SetType const* set,
                            cSetItr itr,
                            ValType const* val[static 1] );
bool remove_from_FuncSuffix( SetType* set, ValType val );
bool set_on_FuncSuffix( SetType* set, ValType val );
/**************************************/
bool intl_erase_in_FuncSuffix( SetType* set, int64_t index, RowType* oldRow );
int64_t intl_index_in_FuncSuffix( SetType* set, uint64_t hash, KeyType key );
bool intl_set_on_FuncSuffix( SetType* set,
                             uint64_t hash,
                             RowType* row,
                             RowType* out );
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ info
=== info

==== set_cap_c
[source,c]
----
int64_t set_cap_c( cSetInfo const info[static 1] );
----

Returns the capacity of a set.

==== set_load_c
[source,c]
----
float set_load_c( cSetInfo const info[static 1] );
----

Returns the load factor of a set.

==== set_is_empty_c
[source,c]
----
bool set_is_empty_c( cSetInfo const info[static 1] );
----

Returns true if a set is empty, otherwise false.


//************************************************************************* itr
=== itr

[id='iterate_set_c_']
==== iterate_set_c_
[source,c]
----
#define iterate_set_c_( Itr, ValPtr, Set, Func )
----

Macro function to define a for statement to iterate over all elements in a map.

.Example
[source,c]
----
include::{xmpldir}/iterate_set.c[]
----

[id='start_set_itr_c']
==== start_set_itr_c
[source,c]
----
cSetItr start_set_itr_c();
----

Function that returns a cSetItr value to get the first value in the set.

[id='set_itr_is_valid_c']
==== set_itr_is_valid_c
[source,c]
----
bool set_itr_is_valid_c( cSetItr itr );
----

Function to check if the iterator is valid.