= CDictionary
:xmpldir: ../../../test/clingo/string/CDictionary

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that defines the CDictionary and the associated functions.

.Example
[source,c]
----
include::{xmpldir}/CDictionary-overview.c[]
----

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='CDictionary']
==== CDictionary
[source,c]
----
struct CDictionary;
typedef struct CDictionary CDictionary;
----

:ObjMap-MapType: CDictionary
:ObjMap-KeyType: CString
:ObjMap-ValType: CString
:ObjMap-FuncSuffix: dictionary_c
include::{docroot}/clingo/_tmpl/ObjMap.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ wrap
=== wrap

==== chars_in_dictionary_c
[source,c]
----
bool chars_in_dictionary_c( CDictionary* dict, cChars key );
----

Util function that wraps in_dictionary_c.

==== cstr_in_dictionary_c
[source,c]
----
bool cstr_in_dictionary_c( CDictionary* dict, char const key[static 1] );
----

Util function that wraps in_dictionary_c.

==== get_via_chars_from_dictionary_c
[source,c]
----
CString* get_via_chars_from_dictionary_c( CDictionary* dict, cChars key );
----

Util function that wraps get_from_dictionary_c.

==== get_via_cstr_from_dictionary_c
[source,c]
----
CString* get_via_cstr_from_dictionary_c( CDictionary* dict,
                                         char const key[static 1] );
----

Util function that wraps get_from_dictionary_c.

==== remove_via_chars_from_dictionary_c
[source,c]
----
bool remove_via_chars_from_dictionary_c( CDictionary* dict, cChars key );
----

Util function that wraps remove_from_dictionary_c.

==== remove_via_cstr_from_dictionary_c
[source,c]
----
bool remove_via_cstr_from_dictionary_c( CDictionary* dict,
                                        char const key[static 1] );
----

Util function that wraps remove_from_dictionary_c.

==== set_chars_on_dictionary_c
[source,c]
----
bool set_chars_on_dictionary_c( CDictionary* dict, cChars key, cChars val );
----

Util function that wraps set_on_dictionary_c.

==== set_cstr_on_dictionary_c
[source,c]
----
bool set_cstr_on_dictionary_c( CDictionary* dict,
                               char const key[static 1],
                               char const val[static 1] );
----

Util function that wraps set_on_dictionary_c.

