= CDictionary
:xmpldir: {testroot}/clingo/string/CDictionary

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that defines the CDictionary and the associated functions.

.Example
[source,c]
----
include::{xmpldir}/CDictionary-overview.c[]
----

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='CDictionary']
==== CDictionary
[source,c]
----
struct CDictionary;
typedef struct CDictionary CDictionary;
----

:ObjMap-MapType: CDictionary
:ObjMap-KeyType: CString
:ObjMap-ValType: CString
:ObjMap-FuncSuffix: dictionary_c
include::{docroot}/clingo/_tmpl/ObjMap.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

=== macros

[id='in_dictionary_c_']
==== in_dictionary_c_
[source,c]
----
#define in_dictionary_c_( Dict, Key )                                          \
   chars_in_dictionary_c( (Dict), c_c( Key) )
----

Macro function that wraps in_dictionary_c.

[id='get_from_dictionary_c_']
==== get_from_dictionary_c_
[source,c]
----
#define get_from_dictionary_c_( Dict, Key )                                    \
   get_via_chars_from_dictionary_c( (Dict), c_c( Key ) )
----

Macro function that wraps get_from_dictionary_c.

[id='remove_from_dictionary_c_']
==== remove_from_dictionary_c_
[source,c]
----
#define remove_from_dictionary_c_( Dict, Key )                                 \
   remove_via_chars_from_dictionary_c( (Dict), c_c( Key ) )
----

Macro function that wraps remove_from_dictionary_c.

[id='set_on_dictionary_c_']
==== set_on_dictionary_c_
[source,c]
----
#define set_on_dictionary_c_( Dict, Key, Val )                                 \
   set_via_chars_on_dictionary_c( (Dict), c_c( Key ), c_c( Val ) )
----

Macro function that wraps set_on_dictionary_c.

//************************************************************************ wrap
=== wrap

==== chars_in_dictionary_c
[source,c]
----
bool chars_in_dictionary_c( CDictionary* dict, cChars key );
----

Util function that wraps in_dictionary_c.

==== get_via_chars_from_dictionary_c
[source,c]
----
CString* get_via_chars_from_dictionary_c( CDictionary* dict, cChars key );
----

Util function that wraps get_from_dictionary_c.

==== remove_via_chars_from_dictionary_c
[source,c]
----
bool remove_via_chars_from_dictionary_c( CDictionary* dict, cChars key );
----

Util function that wraps remove_from_dictionary_c.

==== set_via_chars_on_dictionary_c
[source,c]
----
bool set_via_chars_on_dictionary_c( CDictionary* dict, cChars key, cChars val );
----

Util function that wraps set_on_dictionary_c.
