= cStringBuilder
:xmpldir: {testroot}/clingo/string/cStringBuilder

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that defines the cStringBuilder and functions to build a string.

.Example
[source,c]
----
include::{xmpldir}/CStringBuilder-overview.c[]
----

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cStringBuilder']
==== cStringBuilder
[source,c]
----
struct cStringBuilder
typedef struct cStringBuilder cStringBuilder
----

Abstract type that represents a string builder.

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//********************************************************************** create
=== create

==== init_string_builder_c
[source,c]
----
bool init_string_builder_c( cStringBuilder b[static 1], int64_t cap );
----

Initialise a builder and allocates the memory.
The cap value defines how much the initiale capacity should be.

==== cleanup_string_builder_c
[source,c]
----
void cleanup_string_builder_c( cStringBuilder b[static 1] );
----

Cleanup the the allocated memory.

//********************************************************************** manage
=== manage

==== reset_string_builder_c
[source,c]
----
void reset_string_builder_c( cStringBuilder b[static 1] );
----

Resets the builder.

==== resize_string_builder_c
[source,c]
----
bool resize_string_builder_c( cStringBuilder b[static 1], int64_t cap );
----

Allows to grow or reduce the capacity of a string builder.

==== string_builder_byte_length_c
[source,c]
----
int64_t string_builder_byte_length_c( cStringBuilder b[static 1] );
----

Returns the byte length of the built string without the '\0' character at the
end.

==== string_builder_cap_c
[source,c]
----
int64_t string_builder_cap_c( cStringBuilder b[static 1] );
----

Returns the capacity of the string builder.

==== string_builder_length_c
[source,c]
----
int64_t string_builder_length_c( cStringBuilder b[static 1] );
----

Returns the number of runes of the built string without the '\0' character at
the end.

==== string_builder_space_c
[source,c]
----
int64_ string_builder_space_c( cStringBuilder b[static 1] );
----

Returns the number of bytes that are not allready used.

//********************************************************************** access
=== access

==== built_chars_c
----
cChars built_chars_c( cStringBuilder const b[static 1] );
----

Returns the built string as chars.

==== build_cstr_c
----
char const* built_cstr_c( cStringBuilder const b[static 1] );
----

Returns the built string as C string.

==== turn_into_string_c
----
CString* turn_into_string_c( cStringBuilder b[static 1] );
----

Converts the built string to a CString instance.
The builder transfers the ownership of the internal C string to the CString and
the builder will have 0 capacity.

//********************************************************************** append
=== append

==== append_char_c
[source,c]
----
bool append_char_c( cStringBuilder b[static 1], char c );
----

Appends a char to the string builder.

==== append_chars_c
[source,c]
----
bool append_chars_c( cStringBuilder b[static 1], cChars chars );
----

Appends chars to the string builder.

==== append_cstr_c
[source,c]
----
bool append_cstr_c( cStringBuilder b[static 1], char const cstr[static 1] );
----

Appends a C string to the string builder.

==== append_recorded_c
[source,c]
----
bool append_recorded_c( cStringBuilder b[static 1], cRecorder rec[static 1] );
----

Appends the recorded chars to the string builder.

==== append_rune_c
[source,c]
----
bool append_rune_c( cStringBuilder b[static 1], cRune r );
----

Appends a rune to the string builder.

==== append_string_c
[source,c]
----
bool append_string_c( cStringBuilder b[static 1], CString const* str );
----

Appends a string to the string builder.
