= CStringSet
:xmpldir: ../../../test/clingo/string/CStringSet

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

Module that defines the CStringSet and the associated functions.

.Example
[source,c]
----
include::{xmpldir}/CStringSet-overview.c[]
----

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

//******************************************************************* Generated
=== Generated

[id='CStringSet']
==== CStringSet
[source,c]
----
struct CStringSet;
typedef struct CStringSet CStringSet;
----

Via the macros link:../container/set.html#OBJ_SET_DEF_C_[OBJ_SET_DEF_C_] and
link:../container/set.html#OBJ_SET_IMPL_C_[OBJ_SET_IMPL_C_] declared and
implemented struct.
The macros declare and implement also the following globals and functions.

[source,c]
----
cMeta const C_StringSetMeta;
/* create */
CStringSet* make_string_set_c( int64_t size, float maxLoad );
CStringSet* new_string_set_c();
/* manage */
cSetInfo const* info_of_string_set_c( CStringSet const* set );
bool resize_string_set_c( CStringSet* set, int64_t size );
bool set_max_load_of_string_set_c( CStringSet* set, float maxLoad );
/* api */
bool in_string_set_c( CStringSet const* set, CString const* str );
bool next_in_string_set_c( CStringSet const* set, cSetItr itr[static 1] );
bool remove_from_string_set_c( CStringSet* set, CString const* str );
bool set_on_string_set_c( CStringSet* set, CString* str );
----

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ wrap
=== wrap

==== chars_in_string_set_c
[source,c]
----
bool chars_in_string_set_c( CStringSet* set, cChars val );
----

Util function that wraps in_string_set_c.

==== cstr_in_string_set_c
[source,c]
----
bool cstr_in_string_set_c( CStringSet* set, char const cstr[static 1] );
----

Util function that wraps in_string_set_c.

==== remove_chars_from_string_set_c
[source,c]
----
bool remove_chars_from_string_set_c( CStringSet* set, cChars val );
----

Util function that wraps remove_from_string_set_c.

==== remove_cstr_from_string_set_c
[source,c]
----
bool remove_cstr_from_string_set_c( CStringSet* set,
                                    char const cstr[static 1] );
----

Util function that wraps remove_from_string_set_c.

==== set_chars_on_string_set_c
[source,c]
----
bool set_chars_on_string_set_c( CStringSet* set, cChars val );
----

Util function that wraps set_on_string_set_c.

==== set_cstr_on_string_set_c

[source,c]
----
bool set_cstr_on_string_set_c( CStringSet* set, char const cstr[static 1] );
----

Util function that wraps set_on_string_set_c.

