= cColor
:xmpldir: {testroot}/clingo/color/cColor

include::{docroot}/clingo/_tmpl/attr.adoc[]

//******************************************************************************
//******************************************************************** Overview
//******************************************************************************
== Overview

//******************************************************************************
//******************************************************* Types and Definitions
//******************************************************************************
== Types and Definitions

[id='cColor']
==== cColor
[source,c]
----
struct cColor
{
   uint8_t r;
   uint8_t g;
   uint8_t b;
   uint8_t a;
};
typedef struct cColor cColor;
----

Structs that represents a color value with a alpha channel.
The color value is stored in the RGB color space.

//******************************************************************* Generated
=== Generated

[id='cColorSlice']
==== cColorSlice
:Slice-Type: cColor const
:Slice-Slice: cColorSlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

[id='cVarColorSlice']
==== cVarColorSlice
:Slice-Type: cColor
:Slice-Slice: cVarColorSlice
include::{docroot}/clingo/_tmpl/Slice.adoc[]

//******************************************************************************
//******************************************************************* Functions
//******************************************************************************
== Functions

//************************************************************************ init
=== init

[id='color_c_']
==== color_c_
[source,c]
----
#define color_c_( Red, Green, Blue, Alpha )
----

Creates a transparent color object from decimal red, green, blue and alpha
(RGBA) values.

[id='rgb_color_c']
==== rgb_color_c
[source,c]
----
cColor rgb_color_c( uint32_t raw );
----

Creates a cColor instance from a hex value in the following format RRGGBB.

[id='rgba_color_c']
==== rgba_color_c
[source,c]
----
cColor rgba_color_c( uint32_t raw );
----

Creates a cColor instance from a hex value in the following format RRGGBBAA.

[id='argb_color_c']
==== argb_color_c
[source,c]
----
cColor argb_color_c( uint32_t raw );
----

Creates a cColor instance from a hex value in the following format AARRGGBB.

[id='alpha_color_c']
==== alpha_color_c
[source,c]
----
cColor alpha_color_c( uint8_t red, uint32_t green, uint32_t blue, float alpha );
----

Creats a cColor instance where the alpha value can be set as float (0.0 - 1.0).

//************************************************************************ from
=== from

[id='from_cmyk_c']
==== from_cmyk_c
[source,c]
----
#define from_cmyk_c_( Cyan, Magenta, Yellow, Key )                             \
   from_cmyk_c( cmyk_c_( (Cyan), (Magenta), (Yellow), (Key) ) )
cColor from_cmyk_c( cCmyk cmyk );
----

Creates a cColor value from a cCmyk value.

.Example
[source,c]
----
include::{xmpldir}/from_cmyk.c[]
----

[id='from_cmyk32_c']
==== from_cmyk32_c
[source,c]
----
#define from_cmyk32_c_( Cyan, Magenta, Yellow, Key )                           \
   from_cmyk32_c( cmyk32_c_( (Cyan), (Magenta), (Yellow), (Key) ) )
cColor from_cmyk32_c( cCmyk32 cmyk );
----

Creates a cColor value from a cCmyk32 value.

.Example
[source,c]
----
include::{xmpldir}/from_cmyk32.c[]
----

[id='from_hsl_c']
==== from_hsl_c
[source,c]
----
#define from_hsl_c_( Hue, Saturation, Lightness )                              \
   from_hsl_c( hsl_c_( (Hue), (Saturation), (Lightness) ) )
cColor from_hsl_c( cHsl hsl );
----

Creates a cColor value from a cHsl value.

.Example
[source,c]
----
include::{xmpldir}/from_hsl.c[]
----

[id='from_hsv_c']
==== from_hsv_c
[source,c]
----
#define from_hsv_c_( Hue, Saturation, Value )                                  \
   from_hsv_c( hsv_c_( (Hue), (Saturation), (Value) ) )
cColor from_hsv_c( cHsv hsv );
----

Creates a cColor value from a cHsv value.

.Example
[source,c]
----
include::{xmpldir}/from_hsv.c[]
----

[id='from_rgb_c']
==== from_rgb_c
[source,c]
----
#define from_rgb_c_( Red, Green, Blue )                                        \
   from_rgb_c( rgb_c_( (Red), (Green), (Blue) ) )
cColor from_rgb_c( cRgb rgb );
----

Creates a cColor value from a cRgb value.

.Example
[source,c]
----
include::{xmpldir}/from_rgb.c[]
----

[id='from_rgb24_c']
==== from_rgb24_c
[source,c]
----
#define from_rgb24_c_( Red, Green, Blue )                                      \
   from_rgb24_c( rgb24_c_( (Red), (Green), (Blue) ) )
cColor from_rgb24_c( cRgb24 rgb );
----

Creates a cColor value from a cRgb24 value.

//************************************************************************** as
=== as

[id='as_cmyk_c']
==== as_cmyk_c
[source,c]
----
cCmyk as_cmyk_c( cColor color );
----

Coverts a cColor value to a cCmyk value.

.Example
[source,c]
----
include::{xmpldir}/as_cmyk.c[]
----

[id='as_cmyk32_c']
==== as_cmyk32_c
[source,c]
----
cCmyk32 as_cmyk32_c( cColor color );
----

Coverts a cColor value to a cCmyk32 value.

.Example
[source,c]
----
include::{xmpldir}/as_cmyk32.c[]
----

[id='as_hsl_c']
==== as_hsl_c
[source,c]
----
cHsl as_hsl_c( cColor color );
----

Coverts a cColor value to a cHsl value.

.Example
[source,c]
----
include::{xmpldir}/as_hsl.c[]
----

[id='as_hsv_c']
==== as_hsv_c
[source,c]
----
cHsv as_hsv_c( cColor color );
----

Coverts a cColor value to a cHsv value.

.Example
[source,c]
----
include::{xmpldir}/as_hsv.c[]
----

[id='as_rgb_c']
==== as_rgb_c
[source,c]
----
cRgb as_rgb_c( cColor color );
----

Coverts a cColor value to a cRgb value.

.Example
[source,c]
----
include::{xmpldir}/as_rgb.c[]
----

[id='as_rgb24_c']
==== as_rgb24_c
[source,c]
----
cRgb24 as_rgb24_c( cColor color );
----

Coverts a cColor value to a cRgb24 value.

//************************************************************************* cmp
=== cmp

[id='eq_color_c']
==== eq_color_c
[source,c]
----
bool eq_color_c( cColor a, cColor b );
----

Returns true if both cColor values are equal, otherwise false.

.Example
[source,c]
----
include::{xmpldir}/eq_color.c[]
----

[id='eq_rgb_color_c']
==== eq_rgb_color_c
[source,c]
----
bool eq_rgb_color_c( cColor a, cColor b );
----

Returns true if the RGB values of both cColor values are equal, otherwise false.

//*********************************************************************** alpha
=== alpha

[id='color_alpha_c']
==== color_alpha_c
[source,c]
----
float color_alpha_c( cColor color );
----

Returns the alpha value as float (0.0 - 1.0).

[id='set_color_alpha_c']
==== set_color_alpha_c
[source,c]
----
cColor set_color_alpha_c( cColor color, float alpha );
----

Sets the alpha value via float (0.0 - 1.0).

[id='color_luma_c']
==== color_luma_c
[source,c]
----
float color_luma_c( cColor color );
----

Calculates the luma (perceptual brightness) of a color object.

.Example
[source,c]
----
include::{xmpldir}/color_luma.c[]
----

//****************************************************************** operations
=== operations

[id='saturate_color_c']
==== saturate_color_c
[source,c]
----
cColor saturate_color_c( cColor color, float amount );
----

Increase the saturation of a color in the HSL color space by an absolute amount.

.Example
[source,c]
----
include::{xmpldir}/saturate_color.c[]
----

[id='desaturate_color_c']
==== desaturate_color_c
[source,c]
----
cColor desaturate_color_c( cColor color, float amount );
----

Decrease the saturation of a color in the HSL color space by an absolute amount.

.Example
[source,c]
----
include::{xmpldir}/desaturate_color.c[]
----

[id='lighten_color_c']
==== lighten_color_c
[source,c]
----
cColor lighten_color_c( cColor color, float amount );
----

Increase the lightness of a color in the HSL color space by an absolute amount.

.Example
[source,c]
----
include::{xmpldir}/lighten_color.c[]
----

[id='darken_color_c']
==== darken_color_c
[source,c]
----
cColor darken_color_c( cColor color, float amount );
----

Decrease the lightness of a color in the HSL color space by an absolute amount.

.Example
[source,c]
----
include::{xmpldir}/darken_color.c[]
----

[id='fade_color_c']
==== fade_color_c
[source,c]
----
cColor fade_color_c( cColor color, float amount );
----

Set the absolute opacity of a color.
Can be applied to colors whether they already have an opacity value or not.

.Example
[source,c]
----
include::{xmpldir}/fade_color.c[]
----

[id='spin_color_c']
==== spin_color_c
[source,c]
----
cColor spin_color_c( cColor color, float angle );
----

While the angle range is 0-360, it applies a mod 360 operation, so you can pass
in much larger (or negative) values and they will wrap around e.g. angles of
360 and 720 will produce the same result.

.Example
[source,c]
----
include::{xmpldir}/spin_color.c[]
----

[id='mix_color_c']
==== mix_color_c
[source,c]
----
#define mix_color_c_( Color, Extra ) \
   mix_color_c( Color, Extra, cMIX_COLOR_WEIGHT_ )
cColor mix_color_c( cColor color, cColor extra, float weight );
----

Mix two colors together in variable proportion.
Opacity is included in the calculations.

.Example
[source,c]
----
include::{xmpldir}/mix_color.c[]
----

[id='greyscale_color_c']
==== greyscale_color_c
[source,c]
----
cColor greyscale_color_c( cColor color );
----

Remove all saturation from a color in the HSL color space.

.Example
[source,c]
----
include::{xmpldir}/greyscale_color.c[]
----

[id='contrast_color_c']
==== contrast_color_c
[source,c]
----
#define contrast_color_c_( Color )                                             \
   contrast_color_c( (Color),                                                  \
                     cCONTRAST_COLOR_DARK_,                                    \
                     cCONTRAST_COLOR_LIGHT_,                                   \
                     cCONTRAST_COLOR_THRESHOLD_ )
cColor contrast_color_c( cColor color,
                         cColor dark,
                         cColor light,
                         float threshold );
----

Choose which of two colors provides the greatest contrast with another.

.Example
[source,c]
----
include::{xmpldir}/contrast_color.c[]
----

//******************************************************************** blending
=== blending

[id='multiply_color_c']
==== multiply_color_c
[source,c]
----
cColor multiply_color_c( cColor a, cColor b );
----

Multiply two colors. Corresponding RGB channels from each of the two colors are
multiplied together then divided by 255.
The result is a darker color.

.Example
[source,c]
----
include::{xmpldir}/multiply_color.c[]
----

[id='screen_color_c']
==== screen_color_c
[source,c]
----
cColor screen_color_c( cColor a, cColor b );
----

Do the opposite of multiply.
The result is a brighter color.

.Example
[source,c]
----
include::{xmpldir}/screen_color.c[]
----

[id='overlay_color_c']
==== overlay_color_c
[source,c]
----
cColor overlay_color_c( cColor a, cColor b );
----

Combines the effects of both multiply and screen.
Conditionally make light channels lighter and dark channels darker.

.Example
[source,c]
----
include::{xmpldir}/overlay_color.c[]
----

[id='softlight_color_c']
==== softlight_color_c
[source,c]
----
cColor softlight_color_c( cColor color, cColor extra );
----

Similar to overlay but avoids pure black resulting in pure black, and pure
white resulting in pure white.

.Example
[source,c]
----
include::{xmpldir}/softlight_color.c[]
----

[id='hardlight_color_c']
==== hardlight_color_c
[source,c]
----
cColor hardlight_color_c( cColor color, cColor extra );
----

The same as overlay but with the color roles reversed.

.Example
[source,c]
----
include::{xmpldir}/hardlight_color.c[]
----

[id='difference_color_c']
==== difference_color_c
[source,c]
----
cColor difference_color_c( cColor color, cColor other );
----

Subtracts the second color from the first color on a channel-by-channel basis.
Negative values are inverted.
Subtracting black results in no change; subtracting white results in color
inversion.

.Example
[source,c]
----
include::{xmpldir}/difference_color.c[]
----

[id='exclusion_color_c']
==== exclusion_color_c
[source,c]
----
cColor exclusion_color_c( cColor color, cColor other );
----

A similar effect to difference with lower contrast.

.Example
[source,c]
----
include::{xmpldir}/exclusion_color.c[]
----

[id='average_color_c']
==== average_color_c
[source,c]
----
cColor average_color_c( cColor color, cColor other );
----

Compute the average of two colors on a per-channel (RGB) basis.

.Example
[source,c]
----
include::{xmpldir}/average_color.c[]
----

[id='negation_color_c']
==== negation_color_c
[source,c]
----
cColor negation_color_c( cColor color, cColor other );
----

Do the opposite effect to difference.

.Example
[source,c]
----
include::{xmpldir}/negation_color.c[]
----

//*********************************************************************** image
=== image

[id='heap_var_color_image_c_']
==== heap_var_color_image_c_
[source,c]
----
#define heap_var_color_image_c_( W, H )
----

Allocates the image data at the heap and assigns the memory to a new created
color image.

[id='get_color_pixel_c']
==== get_color_pixel_c
[source,c]
----
cColor get_color_pixel_c( cColorImage image, cPixel pixel );
----

Gets the color of a pixel in a color image.

[id='set_color_pixel_c']
==== set_color_pixel_c
[source,c]
----
void set_color_pixel_c( cVarColorImage image, cPixel pixel, cColor color );
----

Sets the pixel in a color image.